In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", 500)
pd.set_option("display.max_rows", 500)

In [2]:
import xgboost

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier


from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score

from sklearn.metrics import roc_auc_score
from sklearn.metrics import classification_report, confusion_matrix

# Train-Test Split

In [5]:
#importing dataset

In [10]:
df = pd.read_csv(r"C:\Users\Admin\Documents\Winback_Model_Data\HI_Winback_Data_CSV.csv")

In [11]:
df.shape   #Checking shape of the data

(1021128, 42)

In [12]:
 df.head()  # Checking first 5 entries

,POLICYNO,GENDER,OCCUPATION_ORIGINAL,MARITALSTATUS,ISMOBLIE,ISEMAIL,STATE,PINCODE,POLICYSTARTDATE,POLICYENDDATE,POLICYVARIANT,PRODUCT NAME ORIGINAL,PRODUCT CODE ORIGINAL,POLICYTENURE,PLAN TYPE ORIGINAL,STP / NSTP,ISCHRONIC,NET_PREMIUM,SUM_INSURED,SMOKINGCOUNT,ALCOHALCOUNT,AGE,CLAIM_COUNT,HRCNT,ACTIVEDAYS ORIGINAL,ACTIVEDAYS_CNT,HHS_CNT,HA_CNT,APPLOGIN_CNT,ADULT_CNT,CHANNEL,HHS,BUSINESSTYPE,PORTABILITYFLAG,NUMBER_OF_MEMBERS,BMI,REPORTING_YEAR,POLICY_VINTAGE_REVISED,TARGET,DATEDIFFRENEWAL,DATEDIFF_MONTH,RENEWAL_Y/N
0,1000101,M,Self Employed,Single,No,No,GUJARAT,390021,2018-06-19 11:29:51.617,2019-06-18 11:29:51.620,Individual,Activ Health,4212,1,Platinum - Enhanced,NSTP,0,5172.0,500000,0.0,0.0,36,NaN,NaN,0,0.0,0,0,0,<2,TPD,NaN,OTHER,NO,1,27-35,R0,13TH MONTH,0,0,0,N
1,1000102,M,OTH,Married,No,No,KERALA,680587,2020-12-09 00:00:00.000,2021-12-08 00:00:00.000,Family Floater,Activ Health v1.5,4212-v1.5,1,Platinum - Enhanced,STP,0,10890.0,300000,NaN,NaN,39,NaN,NaN,0,0.0,0,0,0,<2,TPD,NaN,Renewal Business,Yes,5,18-27,>R0,>13TH MONTH,0,0,0,N
2,1000103,M,Self Employed,Single,No,No,MADHYA PRADESH,464228,2018-07-06 17:36:23.923,2019-07-05 17:36:23.923,Individual,Activ Health,4212,1,Gold - Enhanced,STP,0,2659.5,200000,0.0,0.0,33,NaN,NaN,0,0.0,0,0,0,<2,TPD,NaN,OTHER,NO,1,18-27,R0,13TH MONTH,0,0,0,N
3,1000104,M,Others,Married,No,No,PUNJAB,152002,2019-01-11 18:52:31.683,2020-01-10 18:52:31.687,Family Floater,Activ Assure,4219,1,Active Assure - Diamond,NSTP,0,11498.0,500000,NaN,NaN,40,NaN,NaN,0,0.0,0,0,0,>=2,TPD,Amber,OTHER,NO,3,NaN,R0,13TH MONTH,0,17,1,Y
4,1000105,M,OTH,Single,No,No,KERALA,670104,2020-07-09 00:00:00.000,2021-07-08 00:00:00.000,Individual,Activ Secure,5000,1,Activ Secure,STP,0,884.0,1000000,NaN,NaN,30,NaN,NaN,0,0.0,0,0,0,<2,TPD,NaN,OTHER,NO,1,18-27,R0,13TH MONTH,0,0,0,N

In [13]:
df.isna().sum()    #Checking the nulls of all the columns

POLICYNO                       0
GENDER                         0
OCCUPATION_ORIGINAL       125885
MARITALSTATUS                  0
ISMOBLIE                       0
ISEMAIL                        0
STATE                          3
PINCODE                        0
POLICYSTARTDATE                0
POLICYENDDATE                  0
POLICYVARIANT                  0
PRODUCT NAME ORIGINAL          0
PRODUCT CODE ORIGINAL          0
POLICYTENURE                   0
PLAN TYPE ORIGINAL             2
STP / NSTP                     2
ISCHRONIC                      0
NET_PREMIUM                    0
SUM_INSURED                    0
SMOKINGCOUNT              780910
ALCOHALCOUNT              781082
AGE                            0
CLAIM_COUNT               946511
HRCNT                     989318
ACTIVEDAYS ORIGINAL            0
ACTIVEDAYS_CNT                 5
HHS_CNT                        0
HA_CNT                         0
APPLOGIN_CNT                   0
ADULT_CNT                      0
CHANNEL                        0
HHS                       675600
BUSINESSTYPE                   0
PORTABILITYFLAG                0
NUMBER_OF_MEMBERS              0
BMI                       257811
REPORTING_YEAR                 0
POLICY_VINTAGE_REVISED         0
TARGET                         0
DATEDIFFRENEWAL                0
DATEDIFF_MONTH                 0
RENEWAL_Y/N                    0
dtype: int64

In [14]:
df.duplicated().sum()

0

In [15]:
df.columns=df.columns.str.upper()    # making all variable headings in capitals

In [16]:
df['TARGET'].value_counts()     # Getting the target count

TARGET
0    955350
1     65778
Name: count, dtype: int64

***Split into 3 parts***
- Training Set: Used to train the model (learn the patterns).
- Validation Set: Used for hyperparameter tuning and to detect overfitting.
- Test Set: Used to evaluate the final model's performance on unseen data

In [18]:
# dividing data into data for train and test and data for validation

In [19]:
data = df.sample(frac = 0.8,random_state=15)
df_val = df.drop(data.index)

In [20]:
#dividing data into train and test

In [21]:
df_train = data.sample(frac = 0.7,random_state=15)
df_test = data.drop(df_train.index)

In [22]:
print('Training set \t :',df_train.shape)
print('Test set \t :',df_test.shape)
print('Val set \t :',df_val.shape)

Training set 	 : (571831, 42)
Test set 	 : (245071, 42)
Val set 	 : (204226, 42)

In [23]:
df_train.head()

,POLICYNO,GENDER,OCCUPATION_ORIGINAL,MARITALSTATUS,ISMOBLIE,ISEMAIL,STATE,PINCODE,POLICYSTARTDATE,POLICYENDDATE,POLICYVARIANT,PRODUCT NAME ORIGINAL,PRODUCT CODE ORIGINAL,POLICYTENURE,PLAN TYPE ORIGINAL,STP / NSTP,ISCHRONIC,NET_PREMIUM,SUM_INSURED,SMOKINGCOUNT,ALCOHALCOUNT,AGE,CLAIM_COUNT,HRCNT,ACTIVEDAYS ORIGINAL,ACTIVEDAYS_CNT,HHS_CNT,HA_CNT,APPLOGIN_CNT,ADULT_CNT,CHANNEL,HHS,BUSINESSTYPE,PORTABILITYFLAG,NUMBER_OF_MEMBERS,BMI,REPORTING_YEAR,POLICY_VINTAGE_REVISED,TARGET,DATEDIFFRENEWAL,DATEDIFF_MONTH,RENEWAL_Y/N
889431,1889532,M,Salaried,Married,No,No,WEST BENGAL,700102,2018-08-24 10:25:06.190,2019-08-23 10:25:06.000,Individual,Activ Secure,5000,1,Activ Secure,STP,0,978.00,1000000,0.0,0.0,34,NaN,NaN,0,0.0,0,0,0,<2,OTHER,NaN,OTHER,NO,1,18-27,R0,13TH MONTH,0,0,0,N
846194,1846295,M,Others,Married,No,No,TELANGANA,500079,2021-01-25 00:00:00.000,2022-01-24 00:00:00.000,Family Floater,Activ Health,4212,1,Platinum - Enhanced,STP,0,12023.00,600000,NaN,NaN,33,NaN,NaN,56,1.0,0,0,1,<2,TPD,Amber,Renewal Business,Yes,2,18-27,>R0,>13TH MONTH,0,0,0,N
492622,1492723,M,OTH,Single,No,No,GUJARAT,361001,2020-07-27 00:00:00.000,2021-07-26 00:00:00.000,Individual,Activ Assure,4219,1,Diamond - Diamond 1,STP,0,4474.80,400000,NaN,NaN,34,NaN,NaN,0,0.0,0,0,0,<2,TPD,NaN,OTHER,NO,1,0-18,R0,13TH MONTH,0,0,0,N
197334,1197435,M,OTH,Married,No,No,ANDHRA PRADESH,531133,2021-03-25 00:00:00.000,2022-03-24 00:00:00.000,Family Floater,Activ Health V2,6212,1,Platinum - Enhanced,STP,0,12405.16,500000,NaN,NaN,37,NaN,NaN,0,0.0,1,0,1,<2,TPD,Green,OTHER,NO,4,18-27,R0,13TH MONTH,0,0,0,N
698020,1698121,F,NaN,Single,No,No,PUNJAB,141414,2019-12-24 10:17:09.177,2020-12-23 00:00:00.000,Individual,Activ Health,4212,1,Gold - Enhanced,STP,0,4745.70,500000,0.0,0.0,24,NaN,NaN,0,0.0,0,0,0,<2,TPD,NaN,OTHER,NO,1,18-27,R0,13TH MONTH,0,0,0,N

In [24]:
# Check the event rate of train
df_train['TARGET'].value_counts(normalize=True)*100

TARGET
0    93.571177
1     6.428823
Name: proportion, dtype: float64

In [25]:
# Check the event rate of test
df_test['TARGET'].value_counts(normalize=True)*100

TARGET
0    93.56717
1     6.43283
Name: proportion, dtype: float64

In [26]:
# Check the event rate of validation
df_val['TARGET'].value_counts(normalize=True)*100

TARGET
0    93.5116
1     6.4884
Name: proportion, dtype: float64

In [27]:
df_train.isna().sum()

POLICYNO                       0
GENDER                         0
OCCUPATION_ORIGINAL        70073
MARITALSTATUS                  0
ISMOBLIE                       0
ISEMAIL                        0
STATE                          3
PINCODE                        0
POLICYSTARTDATE                0
POLICYENDDATE                  0
POLICYVARIANT                  0
PRODUCT NAME ORIGINAL          0
PRODUCT CODE ORIGINAL          0
POLICYTENURE                   0
PLAN TYPE ORIGINAL             1
STP / NSTP                     0
ISCHRONIC                      0
NET_PREMIUM                    0
SUM_INSURED                    0
SMOKINGCOUNT              437840
ALCOHALCOUNT              437936
AGE                            0
CLAIM_COUNT               529952
HRCNT                     554040
ACTIVEDAYS ORIGINAL            0
ACTIVEDAYS_CNT                 3
HHS_CNT                        0
HA_CNT                         0
APPLOGIN_CNT                   0
ADULT_CNT                      0
CHANNEL                        0
HHS                       378578
BUSINESSTYPE                   0
PORTABILITYFLAG                0
NUMBER_OF_MEMBERS              0
BMI                       144545
REPORTING_YEAR                 0
POLICY_VINTAGE_REVISED         0
TARGET                         0
DATEDIFFRENEWAL                0
DATEDIFF_MONTH                 0
RENEWAL_Y/N                    0
dtype: int64

In [28]:
#checking all variable with more than 50% nulls
drop_ = []
for i in df_train.columns:
    if (df_train[i].isna().sum()*100/len(df_train) > 50.000000):
        drop_.append(i)
    else:
        pass

In [29]:
drop_

['SMOKINGCOUNT', 'ALCOHALCOUNT', 'CLAIM_COUNT', 'HRCNT', 'HHS']

In [30]:
#dropping all variable with more than 50% nulls
for column in df_train.columns.to_list():
    if column in drop_:
        df_train.drop(columns = column,axis=1,inplace=True)
        df_test.drop(columns = column,axis=1,inplace=True)    
        df_val.drop(columns = column,axis=1,inplace=True) 
    else:
        pass

In [31]:
print('Training set \t :',df_train.shape)
print('Test set \t :',df_test.shape)
print('Test set \t :',df_val.shape)

Training set 	 : (571831, 37)
Test set 	 : (245071, 37)
Test set 	 : (204226, 37)

In [32]:
df_train['TARGET'].value_counts()

TARGET
0    535069
1     36762
Name: count, dtype: int64

In [36]:
df_train.head()

,POLICYNO,GENDER,OCCUPATION_ORIGINAL,MARITALSTATUS,ISMOBLIE,ISEMAIL,STATE,PINCODE,POLICYSTARTDATE,POLICYENDDATE,POLICYVARIANT,PRODUCT NAME ORIGINAL,PRODUCT CODE ORIGINAL,POLICYTENURE,PLAN TYPE ORIGINAL,STP / NSTP,ISCHRONIC,NET_PREMIUM,SUM_INSURED,AGE,ACTIVEDAYS ORIGINAL,ACTIVEDAYS_CNT,HHS_CNT,HA_CNT,APPLOGIN_CNT,ADULT_CNT,CHANNEL,BUSINESSTYPE,PORTABILITYFLAG,NUMBER_OF_MEMBERS,BMI,REPORTING_YEAR,POLICY_VINTAGE_REVISED,TARGET,DATEDIFFRENEWAL,DATEDIFF_MONTH,RENEWAL_Y/N
889431,1889532,M,Salaried,Married,No,No,WEST BENGAL,700102,2018-08-24 10:25:06.190,2019-08-23 10:25:06.000,Individual,Activ Secure,5000,1,Activ Secure,STP,0,978.00,1000000,34,0,0.0,0,0,0,<2,OTHER,OTHER,NO,1,18-27,R0,13TH MONTH,0,0,0,N
846194,1846295,M,Others,Married,No,No,TELANGANA,500079,2021-01-25 00:00:00.000,2022-01-24 00:00:00.000,Family Floater,Activ Health,4212,1,Platinum - Enhanced,STP,0,12023.00,600000,33,56,1.0,0,0,1,<2,TPD,Renewal Business,Yes,2,18-27,>R0,>13TH MONTH,0,0,0,N
492622,1492723,M,OTH,Single,No,No,GUJARAT,361001,2020-07-27 00:00:00.000,2021-07-26 00:00:00.000,Individual,Activ Assure,4219,1,Diamond - Diamond 1,STP,0,4474.80,400000,34,0,0.0,0,0,0,<2,TPD,OTHER,NO,1,0-18,R0,13TH MONTH,0,0,0,N
197334,1197435,M,OTH,Married,No,No,ANDHRA PRADESH,531133,2021-03-25 00:00:00.000,2022-03-24 00:00:00.000,Family Floater,Activ Health V2,6212,1,Platinum - Enhanced,STP,0,12405.16,500000,37,0,0.0,1,0,1,<2,TPD,OTHER,NO,4,18-27,R0,13TH MONTH,0,0,0,N
698020,1698121,F,NaN,Single,No,No,PUNJAB,141414,2019-12-24 10:17:09.177,2020-12-23 00:00:00.000,Individual,Activ Health,4212,1,Gold - Enhanced,STP,0,4745.70,500000,24,0,0.0,0,0,0,<2,TPD,OTHER,NO,1,18-27,R0,13TH MONTH,0,0,0,N

In [37]:
df_train.isna().sum()

POLICYNO                       0
GENDER                         0
OCCUPATION_ORIGINAL        70073
MARITALSTATUS                  0
ISMOBLIE                       0
ISEMAIL                        0
STATE                          3
PINCODE                        0
POLICYSTARTDATE                0
POLICYENDDATE                  0
POLICYVARIANT                  0
PRODUCT NAME ORIGINAL          0
PRODUCT CODE ORIGINAL          0
POLICYTENURE                   0
PLAN TYPE ORIGINAL             1
STP / NSTP                     0
ISCHRONIC                      0
NET_PREMIUM                    0
SUM_INSURED                    0
AGE                            0
ACTIVEDAYS ORIGINAL            0
ACTIVEDAYS_CNT                 3
HHS_CNT                        0
HA_CNT                         0
APPLOGIN_CNT                   0
ADULT_CNT                      0
CHANNEL                        0
BUSINESSTYPE                   0
PORTABILITYFLAG                0
NUMBER_OF_MEMBERS              0
BMI                       144545
REPORTING_YEAR                 0
POLICY_VINTAGE_REVISED         0
TARGET                         0
DATEDIFFRENEWAL                0
DATEDIFF_MONTH                 0
RENEWAL_Y/N                    0
dtype: int64

In [38]:
# Missing value treatment

In [39]:
mv_dict = {}
#Calculating the median & mode
for i in df_train.columns.to_list():
    if df_train[i].dtype == 'object':
        mv_dict.update({i : df_train[i].mode()[0]})
    else:
        mv_dict.update({i : df_train[i].median()})

#Filling in the null values
for i in df_train.columns.to_list():
    df_train[i].fillna(mv_dict[i], inplace=True)

for i in df_train.columns.to_list():
    df_train[i].replace(np.nan, mv_dict[i], inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_20400\1235064059.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_train[i].fillna(mv_dict[i], inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_20400\1235064059.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_train[i].replace(np.nan, mv_dict[i], inplace=True)

In [40]:
mv_dict

{'POLICYNO': 1509838.0,
 'GENDER': 'M',
 'OCCUPATION_ORIGINAL': 'OTH',
 'MARITALSTATUS': 'Single',
 'ISMOBLIE': 'No',
 'ISEMAIL': 'No',
 'STATE': 'MAHARASHTRA',
 'PINCODE': 400083.0,
 'POLICYSTARTDATE': '2021-03-31 00:00:00.000',
 'POLICYENDDATE': '2022-03-30 00:00:00.000',
 'POLICYVARIANT': 'Individual',
 'PRODUCT NAME ORIGINAL': 'Activ Assure',
 'PRODUCT CODE ORIGINAL': '4219',
 'POLICYTENURE': '1',
 'PLAN TYPE ORIGINAL': 'Active Assure - Diamond',
 'STP / NSTP': 'STP',
 'ISCHRONIC': 0.0,
 'NET_PREMIUM': 7338.95,
 'SUM_INSURED': 500000.0,
 'AGE': 35.0,
 'ACTIVEDAYS ORIGINAL': 0.0,
 'ACTIVEDAYS_CNT': 0.0,
 'HHS_CNT': 0.0,
 'HA_CNT': 0.0,
 'APPLOGIN_CNT': 0.0,
 'ADULT_CNT': '<2',
 'CHANNEL': 'TPD',
 'BUSINESSTYPE': 'OTHER',
 'PORTABILITYFLAG': 'NO',
 'NUMBER_OF_MEMBERS': 1.0,
 'BMI': '18-27',
 'REPORTING_YEAR': 'R0',
 'POLICY_VINTAGE_REVISED': '13TH MONTH',
 'TARGET': 0.0,
 'DATEDIFFRENEWAL': 0.0,
 'DATEDIFF_MONTH': 0.0,
 'RENEWAL_Y/N': 'Y'}

In [41]:
#using the same mean and mode values as of train in test and validation

In [42]:
for i in df_test.columns.to_list():                
    df_test[i].fillna(mv_dict[i], inplace=True)
    
for i in df_test.columns.to_list():
    df_test[i].replace(np.nan, mv_dict[i], inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_20400\2171064033.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_test[i].fillna(mv_dict[i], inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_20400\2171064033.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_test[i].replace(np.nan, mv_dict[i], inplace=True)

In [43]:
for i in df_val.columns.to_list():
    df_val[i].fillna(mv_dict[i], inplace=True)
    
for i in df_val.columns.to_list():
    df_val[i].replace(np.nan, mv_dict[i], inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_20400\2763322074.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_val[i].fillna(mv_dict[i], inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_20400\2763322074.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_val[i].replace(np.nan, mv_dict[i], inplace=True)

In [44]:
df_train.isna().sum()

POLICYNO                  0
GENDER                    0
OCCUPATION_ORIGINAL       0
MARITALSTATUS             0
ISMOBLIE                  0
ISEMAIL                   0
STATE                     0
PINCODE                   0
POLICYSTARTDATE           0
POLICYENDDATE             0
POLICYVARIANT             0
PRODUCT NAME ORIGINAL     0
PRODUCT CODE ORIGINAL     0
POLICYTENURE              0
PLAN TYPE ORIGINAL        0
STP / NSTP                0
ISCHRONIC                 0
NET_PREMIUM               0
SUM_INSURED               0
AGE                       0
ACTIVEDAYS ORIGINAL       0
ACTIVEDAYS_CNT            0
HHS_CNT                   0
HA_CNT                    0
APPLOGIN_CNT              0
ADULT_CNT                 0
CHANNEL                   0
BUSINESSTYPE              0
PORTABILITYFLAG           0
NUMBER_OF_MEMBERS         0
BMI                       0
REPORTING_YEAR            0
POLICY_VINTAGE_REVISED    0
TARGET                    0
DATEDIFFRENEWAL           0
DATEDIFF_MONTH            0
RENEWAL_Y/N               0
dtype: int64

In [45]:
print('Training set \t :',df_train.shape)
print('Test set \t :',df_test.shape)
print('Test set \t :',df_val.shape)

Training set 	 : (571831, 37)
Test set 	 : (245071, 37)
Test set 	 : (204226, 37)

In [46]:
df_train['TARGET'].value_counts()

TARGET
0    535069
1     36762
Name: count, dtype: int64

In [47]:
df_train.columns.tolist()

['POLICYNO',
 'GENDER',
 'OCCUPATION_ORIGINAL',
 'MARITALSTATUS',
 'ISMOBLIE',
 'ISEMAIL',
 'STATE',
 'PINCODE',
 'POLICYSTARTDATE',
 'POLICYENDDATE',
 'POLICYVARIANT',
 'PRODUCT NAME ORIGINAL',
 'PRODUCT CODE ORIGINAL',
 'POLICYTENURE',
 'PLAN TYPE ORIGINAL',
 'STP / NSTP',
 'ISCHRONIC',
 'NET_PREMIUM',
 'SUM_INSURED',
 'AGE',
 'ACTIVEDAYS ORIGINAL',
 'ACTIVEDAYS_CNT',
 'HHS_CNT',
 'HA_CNT',
 'APPLOGIN_CNT',
 'ADULT_CNT',
 'CHANNEL',
 'BUSINESSTYPE',
 'PORTABILITYFLAG',
 'NUMBER_OF_MEMBERS',
 'BMI',
 'REPORTING_YEAR',
 'POLICY_VINTAGE_REVISED',
 'TARGET',
 'DATEDIFFRENEWAL',
 'DATEDIFF_MONTH',
 'RENEWAL_Y/N']

In [48]:
# Keeping a copy of the data as we are going to drop columns as for feature selection
train = df_train.copy()
test = df_test.copy()
val=df_val.copy()

In [49]:
df_train.nunique()

POLICYNO                  571831
GENDER                         2
OCCUPATION_ORIGINAL           39
MARITALSTATUS                  3
ISMOBLIE                       2
ISEMAIL                        2
STATE                         39
PINCODE                    18184
POLICYSTARTDATE           215891
POLICYENDDATE             104861
POLICYVARIANT                  2
PRODUCT NAME ORIGINAL         16
PRODUCT CODE ORIGINAL         16
POLICYTENURE                   2
PLAN TYPE ORIGINAL            32
STP / NSTP                     2
ISCHRONIC                      2
NET_PREMIUM                59812
SUM_INSURED                  219
AGE                           94
ACTIVEDAYS ORIGINAL         2182
ACTIVEDAYS_CNT                11
HHS_CNT                        2
HA_CNT                         2
APPLOGIN_CNT                   2
ADULT_CNT                      2
CHANNEL                        2
BUSINESSTYPE                   2
PORTABILITYFLAG                4
NUMBER_OF_MEMBERS             11
BMI                            4
REPORTING_YEAR                 2
POLICY_VINTAGE_REVISED         2
TARGET                         2
DATEDIFFRENEWAL              656
DATEDIFF_MONTH                32
RENEWAL_Y/N                    2
dtype: int64

In [50]:
# Drop variables which are not required 
df_train.drop(['POLICYNO','ISMOBLIE','ISEMAIL','PINCODE','POLICYSTARTDATE','POLICYENDDATE','ISCHRONIC','SUM_INSURED','HA_CNT','DATEDIFFRENEWAL','DATEDIFF_MONTH','RENEWAL_Y/N'],axis=1,inplace=True)
df_test.drop(['POLICYNO','ISMOBLIE','ISEMAIL','PINCODE','POLICYSTARTDATE','POLICYENDDATE','ISCHRONIC','SUM_INSURED','HA_CNT','DATEDIFFRENEWAL','DATEDIFF_MONTH','RENEWAL_Y/N'],axis=1,inplace=True)
df_val.drop(['POLICYNO','ISMOBLIE','ISEMAIL','PINCODE','POLICYSTARTDATE','POLICYENDDATE','ISCHRONIC','SUM_INSURED','HA_CNT','DATEDIFFRENEWAL','DATEDIFF_MONTH','RENEWAL_Y/N'],axis=1,inplace=True)

In [51]:
df_train.head()

,GENDER,OCCUPATION_ORIGINAL,MARITALSTATUS,STATE,POLICYVARIANT,PRODUCT NAME ORIGINAL,PRODUCT CODE ORIGINAL,POLICYTENURE,PLAN TYPE ORIGINAL,STP / NSTP,NET_PREMIUM,AGE,ACTIVEDAYS ORIGINAL,ACTIVEDAYS_CNT,HHS_CNT,APPLOGIN_CNT,ADULT_CNT,CHANNEL,BUSINESSTYPE,PORTABILITYFLAG,NUMBER_OF_MEMBERS,BMI,REPORTING_YEAR,POLICY_VINTAGE_REVISED,TARGET
889431,M,Salaried,Married,WEST BENGAL,Individual,Activ Secure,5000,1,Activ Secure,STP,978.00,34,0,0.0,0,0,<2,OTHER,OTHER,NO,1,18-27,R0,13TH MONTH,0
846194,M,Others,Married,TELANGANA,Family Floater,Activ Health,4212,1,Platinum - Enhanced,STP,12023.00,33,56,1.0,0,1,<2,TPD,Renewal Business,Yes,2,18-27,>R0,>13TH MONTH,0
492622,M,OTH,Single,GUJARAT,Individual,Activ Assure,4219,1,Diamond - Diamond 1,STP,4474.80,34,0,0.0,0,0,<2,TPD,OTHER,NO,1,0-18,R0,13TH MONTH,0
197334,M,OTH,Married,ANDHRA PRADESH,Family Floater,Activ Health V2,6212,1,Platinum - Enhanced,STP,12405.16,37,0,0.0,1,1,<2,TPD,OTHER,NO,4,18-27,R0,13TH MONTH,0
698020,F,OTH,Single,PUNJAB,Individual,Activ Health,4212,1,Gold - Enhanced,STP,4745.70,24,0,0.0,0,0,<2,TPD,OTHER,NO,1,18-27,R0,13TH MONTH,0

In [52]:
# Droping columns which has only 1 or no value at all
lis=[]
for i in df_train:
    if df_train[i].nunique()==0 or df_train[i].nunique()==1:
        lis.append(i)

In [54]:
lis

[]

In [55]:
df_train.describe(percentiles=[.10,.20,.30,.40,.50,.60,.70,.80,.90,.99])   #Checking variable distribution

,NET_PREMIUM,AGE,ACTIVEDAYS ORIGINAL,ACTIVEDAYS_CNT,HHS_CNT,APPLOGIN_CNT,NUMBER_OF_MEMBERS,TARGET
count,571831.000000,571831.000000,571831.000000,571831.000000,571831.000000,571831.000000,571831.000000,571831.000000
mean,9348.371286,36.751089,33.288491,0.316429,0.133134,0.333230,1.941028,0.064288
std,9626.659635,10.385255,201.584553,0.850517,0.339720,0.471368,1.207993,0.245266
min,-369661.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
10%,2351.000000,25.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
20%,3781.500000,28.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
30%,4908.000000,30.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
40%,5664.700000,33.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
50%,7338.950000,35.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
60%,9018.000000,38.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000
70%,10789.200000,41.000000,0.000000,0.000000,0.000000,1.000000,3.000000,0.000000
80%,13312.000000,45.000000,0.000000,0.000000,0.000000,1.000000,3.000000,0.000000
90%,17630.390000,51.000000,14.000000,2.000000,1.000000,1.000000,4.000000,0.000000
99%,42281.454000,64.000000,928.000000,3.000000,1.000000,1.000000,5.000000,1.000000
max,782306.830000,97.000000,10428.000000,10.000000,1.000000,1.000000,11.000000,1.000000

***Calculating information gain for all the variables***
- This is one of the ways to feature selection
- This can be used for XGboost,Gradient boosting and other tree based algorithms
- higher the info_gain better the feature for selection

In [57]:
import math

In [58]:
#Calculating Entropy
def calc_entropy(column):
    counts = np.bincount(column)
    probabilities = counts / len(column)
    return -sum(p * math.log(p, 2) for p in probabilities if p > 0)

#Calculating Information Gain
def calc_information_gain(data, feature, target):
    original_entropy = calc_entropy(data[target])
    values = data[feature].unique()

    weighted_entropy = 0
    for value in values:
        subset = data[data[feature] == value]
        weight = len(subset) / len(data)
        weighted_entropy += weight * calc_entropy(subset[target])
    
    return original_entropy - weighted_entropy

#Calculating info gain for all features
def get_information_gain_df(df, target):
    info_gain = {
        col: calc_information_gain(df, col, target)
        for col in df.columns if col != target
    }
    result_df = pd.DataFrame(info_gain.items(), columns=['Feature', 'Info Gain'])
    return result_df[result_df['Info Gain'] >= 0]

#Calling the function
df_inf_gain = get_information_gain_df(df_train, 'TARGET')
print(df_inf_gain)

                   Feature  Info Gain
0                   GENDER   0.000173
1      OCCUPATION_ORIGINAL   0.002457
2            MARITALSTATUS   0.001137
3                    STATE   0.001644
4            POLICYVARIANT   0.000842
5    PRODUCT NAME ORIGINAL   0.002337
6    PRODUCT CODE ORIGINAL   0.002640
7             POLICYTENURE   0.005224
8       PLAN TYPE ORIGINAL   0.003556
9               STP / NSTP   0.000015
10             NET_PREMIUM   0.063336
11                     AGE   0.000632
12     ACTIVEDAYS ORIGINAL   0.003445
13          ACTIVEDAYS_CNT   0.001476
14                 HHS_CNT   0.002093
15            APPLOGIN_CNT   0.001242
16               ADULT_CNT   0.017623
17                 CHANNEL   0.002367
18            BUSINESSTYPE   0.001319
19         PORTABILITYFLAG   0.001672
20       NUMBER_OF_MEMBERS   0.001112
21                     BMI   0.006754
22          REPORTING_YEAR   0.001242
23  POLICY_VINTAGE_REVISED   0.000008

In [59]:
# Making all the character values in capitals
for i in df_train.columns.to_list():
    if (df_train[i].dtype == 'object'):
        df_train[i] = df_train[i].str.upper()
        
for i in df_test.columns.to_list():
    if (df_test[i].dtype == 'object'):
        df_test[i] = df_test[i].str.upper()
        
for i in df_val.columns.to_list():
    if (df_val[i].dtype == 'object') & (i!='POL_BILL_TYP_CD'):
        df_val[i] = df_val[i].str.upper()

In [60]:
df_train.head()

,GENDER,OCCUPATION_ORIGINAL,MARITALSTATUS,STATE,POLICYVARIANT,PRODUCT NAME ORIGINAL,PRODUCT CODE ORIGINAL,POLICYTENURE,PLAN TYPE ORIGINAL,STP / NSTP,NET_PREMIUM,AGE,ACTIVEDAYS ORIGINAL,ACTIVEDAYS_CNT,HHS_CNT,APPLOGIN_CNT,ADULT_CNT,CHANNEL,BUSINESSTYPE,PORTABILITYFLAG,NUMBER_OF_MEMBERS,BMI,REPORTING_YEAR,POLICY_VINTAGE_REVISED,TARGET
889431,M,SALARIED,MARRIED,WEST BENGAL,INDIVIDUAL,ACTIV SECURE,5000,1,ACTIV SECURE,STP,978.00,34,0,0.0,0,0,<2,OTHER,OTHER,NO,1,18-27,R0,13TH MONTH,0
846194,M,OTHERS,MARRIED,TELANGANA,FAMILY FLOATER,ACTIV HEALTH,4212,1,PLATINUM - ENHANCED,STP,12023.00,33,56,1.0,0,1,<2,TPD,RENEWAL BUSINESS,YES,2,18-27,>R0,>13TH MONTH,0
492622,M,OTH,SINGLE,GUJARAT,INDIVIDUAL,ACTIV ASSURE,4219,1,DIAMOND - DIAMOND 1,STP,4474.80,34,0,0.0,0,0,<2,TPD,OTHER,NO,1,0-18,R0,13TH MONTH,0
197334,M,OTH,MARRIED,ANDHRA PRADESH,FAMILY FLOATER,ACTIV HEALTH V2,6212,1,PLATINUM - ENHANCED,STP,12405.16,37,0,0.0,1,1,<2,TPD,OTHER,NO,4,18-27,R0,13TH MONTH,0
698020,F,OTH,SINGLE,PUNJAB,INDIVIDUAL,ACTIV HEALTH,4212,1,GOLD - ENHANCED,STP,4745.70,24,0,0.0,0,0,<2,TPD,OTHER,NO,1,18-27,R0,13TH MONTH,0

In [61]:
df_inf_gain.to_excel(r'HI_WinBack_MODEL.xlsx',index=False)

# Variable Binning

In [63]:
# !pip install --upgrade matplotlib

In [64]:
# !pip install scorecardpy

In [65]:
# !pip install --upgrade matplotlib
# Bivariate analysis for all the variables
import matplotlib.pyplot as plt
import seaborn as sns
import scorecardpy as sc
dict1={}
%matplotlib inline

error_cols=[]
df123=pd.DataFrame()
dict123={}
iv={}
for col in df_train.columns:
    try:
        Max = df_train[[col, 'TARGET']]
        bins = sc.woebin(Max, y = 'TARGET')
        
        df123=pd.concat([df123,bins[col]],axis=0)
        dict123[col]=bins[col]
        iv[col]=bins[col]['total_iv'][0]
    except:
        print('error',col)
        error_cols.append(col)

[INFO] creating woe binning ...

C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:446: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\

[INFO] creating woe binning ...

C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:446: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:446: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:446: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\

[INFO] creating woe binning ...

C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:446: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:446: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\

[INFO] creating woe binning ...

C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:446: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:446: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:446: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\

[INFO] creating woe binning ...

C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:446: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\

[INFO] creating woe binning ...

C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:446: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:446: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:446: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\

[INFO] creating woe binning ...

C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:446: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:446: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:446: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\

[INFO] creating woe binning ...

C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:446: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\

[INFO] creating woe binning ...

C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:446: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:446: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:446: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\

[INFO] creating woe binning ...

C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:446: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\

[INFO] creating woe binning ...

C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:320: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  init_bin = dtm.groupby('bin', group_keys=False)['y'].agg([n0, n1])\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:442: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:443: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index().assign(bin=lambda x: x['bstbin'])\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:443: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index().assign(bin=lambda x: x['bstbin'])\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:442: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:443: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index().assign(bin=lambda x: x['bstbin'])\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:443: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index().assign(bin=lambda x: x['bstbin'])\

[INFO] creating woe binning ...

C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:320: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  init_bin = dtm.groupby('bin', group_keys=False)['y'].agg([n0, n1])\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:442: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:443: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index().assign(bin=lambda x: x['bstbin'])\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:443: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index().assign(bin=lambda x: x['bstbin'])\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:442: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:443: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index().assign(bin=lambda x: x['bstbin'])\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:443: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index().assign(bin=lambda x: x['bstbin'])\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:442: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:443: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index().assign(bin=lambda x: x['bstbin'])\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:443: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index().assign(bin=lambda x: x['bstbin'])\

[INFO] creating woe binning ...

C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:320: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  init_bin = dtm.groupby('bin', group_keys=False)['y'].agg([n0, n1])\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:442: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:443: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index().assign(bin=lambda x: x['bstbin'])\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:443: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index().assign(bin=lambda x: x['bstbin'])\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:442: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:443: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index().assign(bin=lambda x: x['bstbin'])\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:443: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index().assign(bin=lambda x: x['bstbin'])\

[INFO] creating woe binning ...

C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:320: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  init_bin = dtm.groupby('bin', group_keys=False)['y'].agg([n0, n1])\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:442: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:443: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index().assign(bin=lambda x: x['bstbin'])\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:443: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index().assign(bin=lambda x: x['bstbin'])\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:442: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:443: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index().assign(bin=lambda x: x['bstbin'])\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:443: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index().assign(bin=lambda x: x['bstbin'])\

[INFO] creating woe binning ...

C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:320: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  init_bin = dtm.groupby('bin', group_keys=False)['y'].agg([n0, n1])\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:413: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby(['variable', 'bstbin', 'value'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:442: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:443: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index().assign(bin=lambda x: x['bstbin'])\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:443: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index().assign(bin=lambda x: x['bstbin'])\

[INFO] creating woe binning ...

C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:320: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  init_bin = dtm.groupby('bin', group_keys=False)['y'].agg([n0, n1])\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:413: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby(['variable', 'bstbin', 'value'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:442: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:443: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index().assign(bin=lambda x: x['bstbin'])\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:443: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index().assign(bin=lambda x: x['bstbin'])\

[INFO] creating woe binning ...

C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:446: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\

[INFO] creating woe binning ...

C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:446: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\

[INFO] creating woe binning ...

C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:446: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\

[INFO] creating woe binning ...

C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:446: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\

[INFO] creating woe binning ...

C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:320: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  init_bin = dtm.groupby('bin', group_keys=False)['y'].agg([n0, n1])\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:361: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  init_bin = init_bin.groupby('brkp', group_keys=False).agg({
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:442: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:443: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index().assign(bin=lambda x: x['bstbin'])\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:443: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index().assign(bin=lambda x: x['bstbin'])\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:442: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:443: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index().assign(bin=lambda x: x['bstbin'])\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:443: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index().assign(bin=lambda x: x['bstbin'])\

[INFO] creating woe binning ...

C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:446: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:446: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:446: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\

[INFO] creating woe binning ...

C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:446: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\

[INFO] creating woe binning ...

C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\condition_fun.py:40: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  datetime_cols = dat.apply(pd.to_numeric,errors='ignore').select_dtypes(object).apply(pd.to_datetime,errors='ignore').select_dtypes('datetime64').columns.tolist()

[INFO] creating woe binning ...
error TARGET

C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:414: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:446: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  binning_1bst_brk = binning_1bst_brk.groupby(['variable', 'bstbin'], group_keys=False)\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\
C:\Users\Admin\anaconda3\Lib\site-packages\scorecardpy\woebin.py:447: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({'good':sum, 'bad':sum, 'bin':lambda x:'%,%'.join(x)}).reset_index()\

In [66]:
for i in dict123.keys():
    dict123[i]['percentage']=round(dict123[i]['badprob'],4)

In [67]:
# !pip install XlsxWriter

In [68]:
from xlsxwriter.workbook import Workbook
import re

def clean_sheetname(name):
    # Remove invalid characters and trim length
    clean_name = re.sub(r'[\\/*?:\[\]]', '', name)
    return clean_name.strip()[:30]

workbook = Workbook('HI_WinBack_MODEL.xlsx')
worksheet = {}

for key in dict123.keys():
    sheet_name = clean_sheetname(key)
    worksheet[key] = workbook.add_worksheet(sheet_name)

    # Formatting
    bold = workbook.add_format({'bold': True})

    # Prepare headings and data
    headings = [key, 'No of Owners', 'TARGET']
    data = dict123[key][['bin', 'count', 'percentage']].T.values

    worksheet[key].write_row('A1', headings, bold)
    worksheet[key].write_column('A2', data[0])
    worksheet[key].write_column('B2', data[1])
    worksheet[key].write_column('C2', data[2])

    row_count = dict123[key].shape[0]
    # Wrap sheet name in quotes for chart formulas
    quoted_sheet = f"'{sheet_name}'"

    # Create column chart
    column_chart = workbook.add_chart({'type': 'column'})
    column_chart.add_series({
        'name':       f'={quoted_sheet}!$B$1',
        'categories': f'={quoted_sheet}!$A$2:$A${row_count + 1}',
        'values':     f'={quoted_sheet}!$B$2:$B${row_count + 1}',
        'data_labels': {'value': True},
        'major_gridlines': {'visible': False}
    })

    # Create line chart (secondary axis)
    line_chart = workbook.add_chart({'type': 'line'})
    line_chart.add_series({
        'name':       f'={quoted_sheet}!$C$1',
        'categories': f'={quoted_sheet}!$A$2:$A${row_count + 1}',
        'values':     f'={quoted_sheet}!$C$2:$C${row_count + 1}',
        'y2_axis':    True,
        'data_labels': {'value': True}
    })

    # Combine charts
    column_chart.combine(line_chart)

    column_chart.set_title({'name': key})
    column_chart.set_x_axis({'name': 'Bins'})
    column_chart.set_y_axis({
        'name': 'Owner Counts',
        'major_gridlines': {'visible': False}
    })
    line_chart.set_y2_axis({'name': 'Event Rate'})
    column_chart.set_legend({'position': 'bottom'})

    # Insert chart
    worksheet[key].insert_chart('F2', column_chart)

workbook.close()

In [69]:
print("Shape of Train data: ",df_train.shape)
print("Shape of Valid data: ",df_val.shape)
print("Shape of Test data: ",df_test.shape)

Shape of Train data:  (571831, 25)
Shape of Valid data:  (204226, 25)
Shape of Test data:  (245071, 25)

In [70]:
df_train.head()

,GENDER,OCCUPATION_ORIGINAL,MARITALSTATUS,STATE,POLICYVARIANT,PRODUCT NAME ORIGINAL,PRODUCT CODE ORIGINAL,POLICYTENURE,PLAN TYPE ORIGINAL,STP / NSTP,NET_PREMIUM,AGE,ACTIVEDAYS ORIGINAL,ACTIVEDAYS_CNT,HHS_CNT,APPLOGIN_CNT,ADULT_CNT,CHANNEL,BUSINESSTYPE,PORTABILITYFLAG,NUMBER_OF_MEMBERS,BMI,REPORTING_YEAR,POLICY_VINTAGE_REVISED,TARGET
889431,M,SALARIED,MARRIED,WEST BENGAL,INDIVIDUAL,ACTIV SECURE,5000,1,ACTIV SECURE,STP,978.00,34,0,0.0,0,0,<2,OTHER,OTHER,NO,1,18-27,R0,13TH MONTH,0
846194,M,OTHERS,MARRIED,TELANGANA,FAMILY FLOATER,ACTIV HEALTH,4212,1,PLATINUM - ENHANCED,STP,12023.00,33,56,1.0,0,1,<2,TPD,RENEWAL BUSINESS,YES,2,18-27,>R0,>13TH MONTH,0
492622,M,OTH,SINGLE,GUJARAT,INDIVIDUAL,ACTIV ASSURE,4219,1,DIAMOND - DIAMOND 1,STP,4474.80,34,0,0.0,0,0,<2,TPD,OTHER,NO,1,0-18,R0,13TH MONTH,0
197334,M,OTH,MARRIED,ANDHRA PRADESH,FAMILY FLOATER,ACTIV HEALTH V2,6212,1,PLATINUM - ENHANCED,STP,12405.16,37,0,0.0,1,1,<2,TPD,OTHER,NO,4,18-27,R0,13TH MONTH,0
698020,F,OTH,SINGLE,PUNJAB,INDIVIDUAL,ACTIV HEALTH,4212,1,GOLD - ENHANCED,STP,4745.70,24,0,0.0,0,0,<2,TPD,OTHER,NO,1,18-27,R0,13TH MONTH,0

In [71]:
df_train.columns

Index(['GENDER', 'OCCUPATION_ORIGINAL', 'MARITALSTATUS', 'STATE',
       'POLICYVARIANT', 'PRODUCT NAME ORIGINAL', 'PRODUCT CODE ORIGINAL',
       'POLICYTENURE', 'PLAN TYPE ORIGINAL', 'STP / NSTP', 'NET_PREMIUM',
       'AGE', 'ACTIVEDAYS ORIGINAL', 'ACTIVEDAYS_CNT', 'HHS_CNT',
       'APPLOGIN_CNT', 'ADULT_CNT', 'CHANNEL', 'BUSINESSTYPE',
       'PORTABILITYFLAG', 'NUMBER_OF_MEMBERS', 'BMI', 'REPORTING_YEAR',
       'POLICY_VINTAGE_REVISED', 'TARGET'],
      dtype='object')

In [72]:
df_train['MARITALSTATUS'].value_counts()

MARITALSTATUS
SINGLE     349327
MARRIED    217026
OTHER        5478
Name: count, dtype: int64

In [73]:
#Binning for Marital Status
def bin_marital_status(df):
    conditions = [
        df['MARITALSTATUS'].isin(['MARRIED']),
    ]
    values = ['GROUP1']
    df['MARITALSTATUS_BIN'] = np.select(conditions, values, default='GROUP2')
    return df

# Apply to all datasets
df_train = bin_marital_status(df_train)
df_test = bin_marital_status(df_test)
df_val = bin_marital_status(df_val)

In [74]:
print('Value counts in MARITALSTATUS in train data: \n',df_train['MARITALSTATUS_BIN'].value_counts())
print('Value counts in MARITALSTATUS in val data: \n',df_val['MARITALSTATUS_BIN'].value_counts())
print('Value counts in MARITALSTATUS in test data: \n',df_test['MARITALSTATUS_BIN'].value_counts())

Value counts in MARITALSTATUS in train data:
 MARITALSTATUS_BIN
GROUP2    354805
GROUP1    217026
Name: count, dtype: int64
Value counts in MARITALSTATUS in val data:
 MARITALSTATUS_BIN
GROUP2    126422
GROUP1     77804
Name: count, dtype: int64
Value counts in MARITALSTATUS in test data:
 MARITALSTATUS_BIN
GROUP2    151912
GROUP1     93159
Name: count, dtype: int64

In [75]:
df_train['OCCUPATION_ORIGINAL'].value_counts()

OCCUPATION_ORIGINAL
OTH                                                   238500
OTHERS                                                140413
SELF EMPLOYED                                          73892
SALARIED                                               67834
PRIVATE SERVICE                                        23987
HOUSE WIFE                                              9368
GOVERNMENT EMPLOYEE                                     5439
0                                                       5362
STUDENT                                                 3646
BUSINESS                                                 991
RETIRED                                                  877
EMPLOYEE                                                 555
BUSINESSMEN                                              321
BUSINESS1                                                218
SMALL & MARGINAL FARMERS                                  85
NOT EMPLOYED                                              56
CLERICAL & ADMINISTRATIVE FUNCTIONS                       48
DOCTORS                                                   46
LAWYERS                                                   39
TEACHERS                                                  35
ENGINEERS                                                 27
ACCOUNTANTS                                               26
IT PROFESSIONALS                                          12
DRIVERS                                                   12
WORKERS                                                   11
BANKERS                                                    8
WOOD WORKING MACHINISTS                                    6
OTHER                                                      5
MASS AFFLUENT                                              3
BUILDERS                                                   2
PERSONS ENGAGED IN ADVENTUROUS  SPORTS                     1
URBAN ASPIRER                                              1
PERSONS WORKING AS AIR CREW AND SHIP CREW                  1
SPORTSMEN                                                  1
ARCHITECTS                                                 1
ENGINEERS ON SITE ENGAGED IN SUPERINTENDING FUNCTI         1
CONTRACTORS                                                1
Name: count, dtype: int64

In [78]:
#Binning Occupation
def bin_occupation(df):
    conditions = [
        df['OCCUPATION_ORIGINAL'].isin(['SALARIED','PRIVATE SERVICE','GOVERNMENT EMPLOYEE',
                                        'EMPLOYEE','CLERICAL & ADMINISTRATIVE FUNCTIONS','TEACHERS',
                                        'ENGINEERS','ACCOUNTANTS','IT PROFESSIONALS','DRIVERS','WORKERS',
                                       'BANKERS','MASS AFFLUENT','PERSONS ENGAGED IN ADVENTUROUS  SPORTS',
                                       'PERSONS WORKING AS AIR CREW AND SHIP CREW','URBAN ASPIRER','SPORTSMEN',
                                       'ENGINEERS ON SITE ENGAGED IN SUPERINTENDING FUNCTI']),
        df['OCCUPATION_ORIGINAL'].isin(['SELF EMPLOYED','BUSINESS','BUSINESSMEN','BUSINESS1','SMALL & MARGINAL FARMERS',
                                        'DOCTORS','LAWYERS','WOOD WORKING MACHINISTS','BUILDERS','ARCHITECTS','CONTRACTORS']),
        df['OCCUPATION_ORIGINAL'].isin(['HOUSE WIFE','STUDENT','RETIRED','NOT EMPLOYED'])
    ]
    values = ['GROUP1', 'GROUP2', 'GROUP3']
    df['OCCUPATION_BIN'] = np.select(conditions, values, default='GROUP4')
    return df

# Apply to all datasets
df_train = bin_occupation(df_train)
df_test = bin_occupation(df_test)
df_val = bin_occupation(df_val)

In [81]:
print('Value counts in OCCUPATION_BIN in train data: \n',df_train['OCCUPATION_BIN'].value_counts())
print('Value counts in OCCUPATION_BIN in val data: \n',df_val['OCCUPATION_BIN'].value_counts())
print('Value counts in OCCUPATION_BIN in test data: \n',df_test['OCCUPATION_BIN'].value_counts())

Value counts in OCCUPATION_BIN in train data:
 OCCUPATION_BIN
GROUP4    384280
GROUP1     98002
GROUP2     75602
GROUP3     13947
Name: count, dtype: int64
Value counts in OCCUPATION_BIN in val data:
 OCCUPATION_BIN
GROUP4    137252
GROUP1     34897
GROUP2     27009
GROUP3      5068
Name: count, dtype: int64
Value counts in OCCUPATION_BIN in test data:
 OCCUPATION_BIN
GROUP4    164630
GROUP1     41912
GROUP2     32558
GROUP3      5971
Name: count, dtype: int64

In [82]:
#Binning State
def bin_state(df):
    conditions = [
        df['STATE'].isin(['LAKSHADWEEP','MIZORAM','DAMAN & DIU','DADRA & NAGAR HAVELI','ANDAMAN & NICOBAR ISLANDS',
                                        'HIMACHAL PRADESH','GOA','CHANDIGARH','PUNJAB']),
        df['STATE'].isin(['JAMMU & KASHMIR','UTTAR PRADESH','HARYANA','CHATTISGARH','PONDICHERRY','MADHYA PRADESH',
                                        'GUJARAT','TELANGANA','DELHI','ANDHRA PRADESH','RAJASTHAN','TAMIL NADU','UTTARAKHAND','TRIPURA']),
        df['STATE'].isin(['JHARKHAND','MAHARASHTRA','KARNATAKA','BIHAR','DEFAULT DISTRICT']),
        df['STATE'].isin(['SIKKIM','KERALA','WEST BENGAL','MEGHALAYA','ODISHA','ARUNACHAL PRADESH','MANIPUR','ASSAM',
                                        'NAGALAND','DEFAULT STATE'])
    ]
    values = ['GROUP1', 'GROUP2', 'GROUP3', 'GROUP4']
    df['STATE_BIN'] = np.select(conditions, values, default='GROUP5')
    return df

# Apply to all datasets
df_train = bin_state(df_train)
df_test = bin_state(df_test)
df_val = bin_state(df_val)

In [83]:
print('Value counts in STATE_BIN in train data: \n',df_train['STATE_BIN'].value_counts())
print('Value counts in STATE_BIN in val data: \n',df_val['STATE_BIN'].value_counts())
print('Value counts in STATE_BIN in test data: \n',df_test['STATE_BIN'].value_counts())

Value counts in STATE_BIN in train data:
 STATE_BIN
GROUP2    324859
GROUP3    149391
GROUP4     62923
GROUP1     34658
Name: count, dtype: int64
Value counts in STATE_BIN in val data:
 STATE_BIN
GROUP2    116103
GROUP3     53386
GROUP4     22368
GROUP1     12369
Name: count, dtype: int64
Value counts in STATE_BIN in test data:
 STATE_BIN
GROUP2    139176
GROUP3     64029
GROUP4     27058
GROUP1     14808
Name: count, dtype: int64

In [84]:
#Binning Product Name
def bin_productname(df):
    conditions = [
        df['PRODUCT NAME ORIGINAL'].isin(['POS ACTIV SECURE','AROGYA SANJEEVANI POLICY','ACTIV SECURE']),
        df['PRODUCT NAME ORIGINAL'].isin(['ACTIV CARE V2','ACTIV ASSURE','SUPER TOP UP']),
        df['PRODUCT NAME ORIGINAL'].isin(['POS ACTIV ASSURE','ACTIV HEALTH V2','ACTIV HEALTH','ACTIV HEALTH V1.5','ACTIV CARE',
                                        'SUPER HEALTH PLUS TOP UP','GLOBAL HEALTH SECURE','GLOBAL HEALTH SECURE - REVISED',
                                        'GLOBAL HEALTH SECURE - AS IS','ACTIV ASSURE V2'])
    ]
    values = ['GROUP1', 'GROUP2', 'GROUP3']
    df['PRODUCT NAME_BIN'] = np.select(conditions, values, default='GROUP4')
    return df

# Apply to all datasets
df_train = bin_productname(df_train)
df_test = bin_productname(df_test)
df_val = bin_productname(df_val)

In [85]:
print('Value counts in PRODUCT NAME_BIN in train data: \n',df_train['PRODUCT NAME_BIN'].value_counts())
print('Value counts in PRODUCT NAME_BIN in val data: \n',df_val['PRODUCT NAME_BIN'].value_counts())
print('Value counts in PRODUCT NAME_BIN in test data: \n',df_test['PRODUCT NAME_BIN'].value_counts())

Value counts in PRODUCT NAME_BIN in train data:
 PRODUCT NAME_BIN
GROUP2    289197
GROUP3    158354
GROUP1    124280
Name: count, dtype: int64
Value counts in PRODUCT NAME_BIN in val data:
 PRODUCT NAME_BIN
GROUP2    103398
GROUP3     56717
GROUP1     44111
Name: count, dtype: int64
Value counts in PRODUCT NAME_BIN in test data:
 PRODUCT NAME_BIN
GROUP2    124133
GROUP3     67684
GROUP1     53254
Name: count, dtype: int64

In [86]:
#Binning Policy tenure
df_train['POLICYTENURE_BIN'] = df_train['POLICYTENURE'].fillna(0).apply(lambda x: 1 if x == '>1' else x)
df_test['POLICYTENURE_BIN'] = df_test['POLICYTENURE'].fillna(0).apply(lambda x: 1 if x == '>1' else x)
df_val['POLICYTENURE_BIN'] = df_val['POLICYTENURE'].fillna(0).apply(lambda x: 1 if x == '>1' else x)

In [87]:
print("Train data: ",df_train['POLICYTENURE_BIN'].value_counts())
print("Test data: ",df_test['POLICYTENURE_BIN'].value_counts())
print("Val data: ",df_val['POLICYTENURE_BIN'].value_counts())

Train data:  POLICYTENURE_BIN
1    479050
1     92781
Name: count, dtype: int64
Test data:  POLICYTENURE_BIN
1    205268
1     39803
Name: count, dtype: int64
Val data:  POLICYTENURE_BIN
1    171111
1     33115
Name: count, dtype: int64

In [90]:
df_train['POLICYTENURE'].value_counts()

POLICYTENURE
1     479050
>1     92781
Name: count, dtype: int64

In [91]:
#Binning Plan Type
def bin_plantype(df):
    conditions = [
        df['PLAN TYPE ORIGINAL'].isin(['PLATINUM - PREMIERE','POS DIAMOND -','POS ACTIV SECURE','GOLD - ENHANCED',
                                        'AROGYA SANJEEVANI','POS DIAMOND - POS DIAMOND 2','ACTIV SECURE','CLASSIC -','DIAMOND -']),
        df['PLAN TYPE ORIGINAL'].isin(['PLATINUM - ESSENTIAL','ACTIVE ASSURE - DIAMOND']),
        df['PLAN TYPE ORIGINAL'].isin(['DIAMOND - DIAMOND 1','POS DIAMOND PLAN']),
    ]
    values = ['GROUP1', 'GROUP2', 'GROUP3']
    df['PLAN TYPE ORIGINAL_BIN'] = np.select(conditions, values, default='GROUP4')
    return df

# Apply to all datasets
df_train = bin_plantype(df_train)
df_test = bin_plantype(df_test)
df_val = bin_plantype(df_val)

In [92]:
print('Value counts in PLAN TYPE ORIGINAL_BIN in train data: \n',df_train['PLAN TYPE ORIGINAL_BIN'].value_counts())
print('Value counts in PLAN TYPE ORIGINAL_BIN in val data: \n',df_val['PLAN TYPE ORIGINAL_BIN'].value_counts())
print('Value counts in PLAN TYPE ORIGINAL_BIN in test data: \n',df_test['PLAN TYPE ORIGINAL_BIN'].value_counts())

Value counts in PLAN TYPE ORIGINAL_BIN in train data:
 PLAN TYPE ORIGINAL_BIN
GROUP4    228684
GROUP2    142442
GROUP1    136650
GROUP3     64055
Name: count, dtype: int64
Value counts in PLAN TYPE ORIGINAL_BIN in val data:
 PLAN TYPE ORIGINAL_BIN
GROUP4    81946
GROUP2    50972
GROUP1    48541
GROUP3    22767
Name: count, dtype: int64
Value counts in PLAN TYPE ORIGINAL_BIN in test data:
 PLAN TYPE ORIGINAL_BIN
GROUP4    97816
GROUP2    61329
GROUP1    58635
GROUP3    27291
Name: count, dtype: int64

In [93]:
df_train['AGE'].describe()

count    571831.000000
mean         36.751089
std          10.385255
min           1.000000
25%          29.000000
50%          35.000000
75%          43.000000
max          97.000000
Name: AGE, dtype: float64

In [94]:
df_train['AGE'].isna().sum()

0

In [101]:
# Binning AGE
def bin_age(df, col_name='AGE', output_col='AGE_BIN'):
    df[col_name] = df[col_name].fillna(0)
    df[output_col] = df[col_name].apply(
        lambda x: "GROUP1" if 0 <= x < 28 else
                  "GROUP2" if 28 <= x < 34 else
                  "GROUP3" if 34 <= x < 56 else
                  "GROUP4"
    )
    return df

df_train = bin_age(df_train, col_name='AGE', output_col='AGE_GROUPED')
df_test = bin_age(df_test, col_name='AGE', output_col='AGE_GROUPED')
df_val = bin_age(df_val, col_name='AGE', output_col='AGE_GROUPED')

In [102]:
print('Value counts in AGE_BIN train data: \n',df_train['AGE_GROUPED'].value_counts())
print('Value counts in AGE_BIN in val data: \n',df_val['AGE_GROUPED'].value_counts())
print('Value counts in AGE_BIN ORIGINAL_BIN in test data: \n',df_test['AGE_GROUPED'].value_counts())

Value counts in AGE_BIN train data:
 AGE_GROUPED
GROUP3    292222
GROUP2    136492
GROUP1    109630
GROUP4     33487
Name: count, dtype: int64
Value counts in AGE_BIN in val data:
 AGE_GROUPED
GROUP3    104384
GROUP2     48991
GROUP1     39008
GROUP4     11843
Name: count, dtype: int64
Value counts in AGE_BIN ORIGINAL_BIN in test data:
 AGE_GROUPED
GROUP3    125554
GROUP2     58733
GROUP1     46571
GROUP4     14213
Name: count, dtype: int64

In [103]:
df_train['ACTIVEDAYS ORIGINAL'].value_counts()

ACTIVEDAYS ORIGINAL
0       486089
2         4998
6         3615
4         3308
3         3044
         ...
2817         1
1202         1
1803         1
3780         1
1600         1
Name: count, Length: 2182, dtype: int64

In [104]:
#Binning Active Days
df_train['ACTIVEDAYS ORIGINAL_BIN'] = df_train['ACTIVEDAYS ORIGINAL'].fillna(0).apply(lambda x: 0 if x <= 20 else 1)
df_test['ACTIVEDAYS ORIGINAL_BIN'] = df_test['ACTIVEDAYS ORIGINAL'].fillna(0).apply(lambda x: 0 if x <= 20 else 1)
df_val['ACTIVEDAYS ORIGINAL_BIN'] = df_val['ACTIVEDAYS ORIGINAL'].fillna(0).apply(lambda x: 0 if x <= 20 else 1)

In [105]:
print('Value counts in ACTIVEDAYS ORIGINAL_BIN train data: \n',df_train['ACTIVEDAYS ORIGINAL_BIN'].value_counts())
print('Value counts in ACTIVEDAYS ORIGINAL_BIN in val data: \n',df_val['ACTIVEDAYS ORIGINAL_BIN'].value_counts())
print('Value counts in ACTIVEDAYS ORIGINAL_BIN ORIGINAL_BIN in test data: \n',df_test['ACTIVEDAYS ORIGINAL_BIN'].value_counts())

Value counts in ACTIVEDAYS ORIGINAL_BIN train data:
 ACTIVEDAYS ORIGINAL_BIN
0    519757
1     52074
Name: count, dtype: int64
Value counts in ACTIVEDAYS ORIGINAL_BIN in val data:
 ACTIVEDAYS ORIGINAL_BIN
0    185545
1     18681
Name: count, dtype: int64
Value counts in ACTIVEDAYS ORIGINAL_BIN ORIGINAL_BIN in test data:
 ACTIVEDAYS ORIGINAL_BIN
0    222538
1     22533
Name: count, dtype: int64

In [106]:
df_train['ACTIVEDAYS_CNT'].value_counts()

ACTIVEDAYS_CNT
0.0     486089
2.0      34579
1.0      25365
3.0      20916
4.0       2441
6.0       1628
5.0        785
7.0         16
8.0          6
9.0          4
10.0         2
Name: count, dtype: int64

In [108]:
#Binning Active Days count
df_train['ACTIVEDAYS_CNT_BIN'] = df_train['ACTIVEDAYS_CNT'].fillna(0).apply(lambda x: 0 if x <= 2 else 1)
df_test['ACTIVEDAYS_CNT_BIN'] = df_test['ACTIVEDAYS_CNT'].fillna(0).apply(lambda x: 0 if x <= 2 else 1)
df_val['ACTIVEDAYS_CNT_BIN'] = df_val['ACTIVEDAYS_CNT'].fillna(0).apply(lambda x: 0 if x <= 2 else 1)

In [109]:
print('Value counts in ACTIVEDAYS_CNT_BIN train data: \n',df_train['ACTIVEDAYS_CNT_BIN'].value_counts())
print('Value counts in ACTIVEDAYS_CNT_BIN in val data: \n',df_val['ACTIVEDAYS_CNT_BIN'].value_counts())
print('Value counts in ACTIVEDAYS_CNT_BIN ORIGINAL_BIN in test data: \n',df_test['ACTIVEDAYS_CNT_BIN'].value_counts())

Value counts in ACTIVEDAYS_CNT_BIN train data:
 ACTIVEDAYS_CNT_BIN
0    546033
1     25798
Name: count, dtype: int64
Value counts in ACTIVEDAYS_CNT_BIN in val data:
 ACTIVEDAYS_CNT_BIN
0    195104
1      9122
Name: count, dtype: int64
Value counts in ACTIVEDAYS_CNT_BIN ORIGINAL_BIN in test data:
 ACTIVEDAYS_CNT_BIN
0    234033
1     11038
Name: count, dtype: int64

In [110]:
df_train['HHS_CNT'].value_counts()

HHS_CNT
0    495701
1     76130
Name: count, dtype: int64

In [111]:
df_train['APPLOGIN_CNT'].value_counts()

APPLOGIN_CNT
0    381280
1    190551
Name: count, dtype: int64

In [112]:
df_train['ADULT_CNT'].value_counts()

ADULT_CNT
<2     311633
>=2    260198
Name: count, dtype: int64

In [115]:
df_train['CHANNEL'].value_counts()

CHANNEL
TPD      331756
OTHER    240075
Name: count, dtype: int64

In [116]:
df_train['BMI'].value_counts()

BMI
18-27    356137
0-18     128208
>35       46611
27-35     40875
Name: count, dtype: int64

In [117]:
# Binning NUMBER_OF_MEMBERS
def bin_members(df, col_name='NUMBER_OF_MEMBERS', output_col='NUMBER_OF_MEMBERS_BIN'):
    df[col_name] = df[col_name].fillna(0)
    df[output_col] = df[col_name].apply(
        lambda x: "GROUP1" if 0 <= x < 2 else
                  "GROUP2" if 2 <= x < 4 else
                  "GROUP3"
    )
    return df

df_train = bin_members(df_train, col_name='NUMBER_OF_MEMBERS', output_col='NUMBER_OF_MEMBERS_BIN')
df_test = bin_members(df_test, col_name='NUMBER_OF_MEMBERS', output_col='NUMBER_OF_MEMBERS_BIN')
df_val = bin_members(df_val, col_name='NUMBER_OF_MEMBERS', output_col='NUMBER_OF_MEMBERS_BIN')

In [118]:
print('Value counts in NUMBER_OF_MEMBERS_BIN train data: \n',df_train['NUMBER_OF_MEMBERS_BIN'].value_counts())
print('Value counts in NUMBER_OF_MEMBERS_BIN in val data: \n',df_val['NUMBER_OF_MEMBERS_BIN'].value_counts())
print('Value counts in NUMBER_OF_MEMBERS_BIN ORIGINAL_BIN in test data: \n',df_test['NUMBER_OF_MEMBERS_BIN'].value_counts())

Value counts in NUMBER_OF_MEMBERS_BIN train data:
 NUMBER_OF_MEMBERS_BIN
GROUP1    314949
GROUP2    166555
GROUP3     90327
Name: count, dtype: int64
Value counts in NUMBER_OF_MEMBERS_BIN in val data:
 NUMBER_OF_MEMBERS_BIN
GROUP1    112464
GROUP2     59521
GROUP3     32241
Name: count, dtype: int64
Value counts in NUMBER_OF_MEMBERS_BIN ORIGINAL_BIN in test data:
 NUMBER_OF_MEMBERS_BIN
GROUP1    134804
GROUP2     71525
GROUP3     38742
Name: count, dtype: int64

In [119]:
# Drop variables which are not required 
df_train.drop(['PRODUCT CODE ORIGINAL','NET_PREMIUM'],axis=1,inplace=True)
df_test.drop(['PRODUCT CODE ORIGINAL','NET_PREMIUM'],axis=1,inplace=True)
df_val.drop(['PRODUCT CODE ORIGINAL','NET_PREMIUM'],axis=1,inplace=True)

In [120]:
df_train.head()

,GENDER,OCCUPATION_ORIGINAL,MARITALSTATUS,STATE,POLICYVARIANT,PRODUCT NAME ORIGINAL,POLICYTENURE,PLAN TYPE ORIGINAL,STP / NSTP,AGE,ACTIVEDAYS ORIGINAL,ACTIVEDAYS_CNT,HHS_CNT,APPLOGIN_CNT,ADULT_CNT,CHANNEL,BUSINESSTYPE,PORTABILITYFLAG,NUMBER_OF_MEMBERS,BMI,REPORTING_YEAR,POLICY_VINTAGE_REVISED,TARGET,MARITALSTATUS_BIN,OCCUPATION_BIN,STATE_BIN,PRODUCT NAME_BIN,POLICYTENURE_BIN,PLAN TYPE ORIGINAL_BIN,AGE_GROUPED,ACTIVEDAYS ORIGINAL_BIN,ACTIVEDAYS_CNT_BIN,NUMBER_OF_MEMBERS_BIN
889431,M,SALARIED,MARRIED,WEST BENGAL,INDIVIDUAL,ACTIV SECURE,1,ACTIV SECURE,STP,34,0,0.0,0,0,<2,OTHER,OTHER,NO,1,18-27,R0,13TH MONTH,0,GROUP1,GROUP1,GROUP4,GROUP1,1,GROUP1,GROUP3,0,0,GROUP1
846194,M,OTHERS,MARRIED,TELANGANA,FAMILY FLOATER,ACTIV HEALTH,1,PLATINUM - ENHANCED,STP,33,56,1.0,0,1,<2,TPD,RENEWAL BUSINESS,YES,2,18-27,>R0,>13TH MONTH,0,GROUP1,GROUP4,GROUP2,GROUP3,1,GROUP4,GROUP2,1,0,GROUP2
492622,M,OTH,SINGLE,GUJARAT,INDIVIDUAL,ACTIV ASSURE,1,DIAMOND - DIAMOND 1,STP,34,0,0.0,0,0,<2,TPD,OTHER,NO,1,0-18,R0,13TH MONTH,0,GROUP2,GROUP4,GROUP2,GROUP2,1,GROUP3,GROUP3,0,0,GROUP1
197334,M,OTH,MARRIED,ANDHRA PRADESH,FAMILY FLOATER,ACTIV HEALTH V2,1,PLATINUM - ENHANCED,STP,37,0,0.0,1,1,<2,TPD,OTHER,NO,4,18-27,R0,13TH MONTH,0,GROUP1,GROUP4,GROUP2,GROUP3,1,GROUP4,GROUP3,0,0,GROUP3
698020,F,OTH,SINGLE,PUNJAB,INDIVIDUAL,ACTIV HEALTH,1,GOLD - ENHANCED,STP,24,0,0.0,0,0,<2,TPD,OTHER,NO,1,18-27,R0,13TH MONTH,0,GROUP2,GROUP4,GROUP1,GROUP3,1,GROUP1,GROUP1,0,0,GROUP1

In [121]:
print(df_train.shape)
print(df_test.shape)
print(df_val.shape)

(571831, 33)
(245071, 33)
(204226, 33)

In [122]:
# Find columns present in train but not in test or val
extra_cols_train_vs_test = set(df_train.columns) - set(df_test.columns)
extra_cols_train_vs_val = set(df_train.columns) - set(df_val.columns)

# Print results
print("Extra in train vs test:", extra_cols_train_vs_test)
print("Extra in train vs val:", extra_cols_train_vs_val)

Extra in train vs test: set()
Extra in train vs val: set()

In [123]:
print(df_train.shape)
print(df_test.shape)
print(df_val.shape)

(571831, 33)
(245071, 33)
(204226, 33)

In [124]:
# # Save df_train to Train_Data.xlsx
# df_train.to_excel('Train_Data.xlsx', index=False)

# # Save df_val to Validation_Data.xlsx
# df_val.to_excel('Validation_Data.xlsx', index=False)

# # Save df_test to Test_Data.xlsx
# df_test.to_excel('Test_Data.xlsx', index=False)

In [125]:
#Removing the original columns and storing in a new variable

In [126]:
cols_to_drop = [
    'OCCUPATION_ORIGINAL', 'MARITALSTATUS', 'STATE', 'PRODUCT NAME ORIGINAL',
    'POLICYTENURE', 'PLAN TYPE ORIGINAL', 'AGE',
    'ACTIVEDAYS ORIGINAL', 'ACTIVEDAYS_CNT', 'NUMBER_OF_MEMBERS'
]
df_train.drop(cols_to_drop, axis=1, inplace=True)
df_test.drop(cols_to_drop, axis=1, inplace=True)
df_val.drop(cols_to_drop, axis=1, inplace=True)

In [127]:
print(df_train.shape)
print(df_test.shape)
print(df_val.shape)

(571831, 23)
(245071, 23)
(204226, 23)

# Model Development

In [130]:
df_train.head()

,GENDER,POLICYVARIANT,STP / NSTP,HHS_CNT,APPLOGIN_CNT,ADULT_CNT,CHANNEL,BUSINESSTYPE,PORTABILITYFLAG,BMI,REPORTING_YEAR,POLICY_VINTAGE_REVISED,TARGET,MARITALSTATUS_BIN,OCCUPATION_BIN,STATE_BIN,PRODUCT NAME_BIN,POLICYTENURE_BIN,PLAN TYPE ORIGINAL_BIN,AGE_GROUPED,ACTIVEDAYS ORIGINAL_BIN,ACTIVEDAYS_CNT_BIN,NUMBER_OF_MEMBERS_BIN
889431,M,INDIVIDUAL,STP,0,0,<2,OTHER,OTHER,NO,18-27,R0,13TH MONTH,0,GROUP1,GROUP1,GROUP4,GROUP1,1,GROUP1,GROUP3,0,0,GROUP1
846194,M,FAMILY FLOATER,STP,0,1,<2,TPD,RENEWAL BUSINESS,YES,18-27,>R0,>13TH MONTH,0,GROUP1,GROUP4,GROUP2,GROUP3,1,GROUP4,GROUP2,1,0,GROUP2
492622,M,INDIVIDUAL,STP,0,0,<2,TPD,OTHER,NO,0-18,R0,13TH MONTH,0,GROUP2,GROUP4,GROUP2,GROUP2,1,GROUP3,GROUP3,0,0,GROUP1
197334,M,FAMILY FLOATER,STP,1,1,<2,TPD,OTHER,NO,18-27,R0,13TH MONTH,0,GROUP1,GROUP4,GROUP2,GROUP3,1,GROUP4,GROUP3,0,0,GROUP3
698020,F,INDIVIDUAL,STP,0,0,<2,TPD,OTHER,NO,18-27,R0,13TH MONTH,0,GROUP2,GROUP4,GROUP1,GROUP3,1,GROUP1,GROUP1,0,0,GROUP1

In [133]:
df_train.select_dtypes(include='object').head()

,GENDER,POLICYVARIANT,STP / NSTP,ADULT_CNT,CHANNEL,BUSINESSTYPE,PORTABILITYFLAG,BMI,REPORTING_YEAR,POLICY_VINTAGE_REVISED,MARITALSTATUS_BIN,OCCUPATION_BIN,STATE_BIN,PRODUCT NAME_BIN,POLICYTENURE_BIN,PLAN TYPE ORIGINAL_BIN,AGE_GROUPED,NUMBER_OF_MEMBERS_BIN
889431,M,INDIVIDUAL,STP,<2,OTHER,OTHER,NO,18-27,R0,13TH MONTH,GROUP1,GROUP1,GROUP4,GROUP1,1,GROUP1,GROUP3,GROUP1
846194,M,FAMILY FLOATER,STP,<2,TPD,RENEWAL BUSINESS,YES,18-27,>R0,>13TH MONTH,GROUP1,GROUP4,GROUP2,GROUP3,1,GROUP4,GROUP2,GROUP2
492622,M,INDIVIDUAL,STP,<2,TPD,OTHER,NO,0-18,R0,13TH MONTH,GROUP2,GROUP4,GROUP2,GROUP2,1,GROUP3,GROUP3,GROUP1
197334,M,FAMILY FLOATER,STP,<2,TPD,OTHER,NO,18-27,R0,13TH MONTH,GROUP1,GROUP4,GROUP2,GROUP3,1,GROUP4,GROUP3,GROUP3
698020,F,INDIVIDUAL,STP,<2,TPD,OTHER,NO,18-27,R0,13TH MONTH,GROUP2,GROUP4,GROUP1,GROUP3,1,GROUP1,GROUP1,GROUP1

In [135]:
# one hot encoding the variables

In [136]:
c = df_train.columns.to_list()

In [137]:
#Creates a new DataFrame df1 with only the columns listed in c
df1 = df_train[c] 

#Creates a list cat_vars that contains the names of all columns in df1 that are of type object (i.e., categorical).
cat_vars = [i for i in df1.columns if df1[i].dtype == 'object']

for var in cat_vars:
    #ensures the new column names are prefixed with the original column name (to avoid confusion)
    #pd.get_dummies() creates binary (0/1) columns for each category.
    dummies = pd.get_dummies(df1[var], prefix=var) 
    df1 = df1.join(dummies) 

#Now that dummy variables are added, the original object-type columns are no longer needed, so this line removes them.
df1 = df1.drop(cat_vars, axis=1)

In [138]:
df1.head()

,HHS_CNT,APPLOGIN_CNT,TARGET,ACTIVEDAYS ORIGINAL_BIN,ACTIVEDAYS_CNT_BIN,GENDER_F,GENDER_M,POLICYVARIANT_FAMILY FLOATER,POLICYVARIANT_INDIVIDUAL,STP / NSTP_NSTP,STP / NSTP_STP,ADULT_CNT_<2,ADULT_CNT_>=2,CHANNEL_OTHER,CHANNEL_TPD,BUSINESSTYPE_OTHER,BUSINESSTYPE_RENEWAL BUSINESS,PORTABILITYFLAG_NO,PORTABILITYFLAG_YES,BMI_0-18,BMI_18-27,BMI_27-35,BMI_>35,REPORTING_YEAR_>R0,REPORTING_YEAR_R0,POLICY_VINTAGE_REVISED_13TH MONTH,POLICY_VINTAGE_REVISED_>13TH MONTH,MARITALSTATUS_BIN_GROUP1,MARITALSTATUS_BIN_GROUP2,OCCUPATION_BIN_GROUP1,OCCUPATION_BIN_GROUP2,OCCUPATION_BIN_GROUP3,OCCUPATION_BIN_GROUP4,STATE_BIN_GROUP1,STATE_BIN_GROUP2,STATE_BIN_GROUP3,STATE_BIN_GROUP4,PRODUCT NAME_BIN_GROUP1,PRODUCT NAME_BIN_GROUP2,PRODUCT NAME_BIN_GROUP3,POLICYTENURE_BIN_1,POLICYTENURE_BIN_1,PLAN TYPE ORIGINAL_BIN_GROUP1,PLAN TYPE ORIGINAL_BIN_GROUP2,PLAN TYPE ORIGINAL_BIN_GROUP3,PLAN TYPE ORIGINAL_BIN_GROUP4,AGE_GROUPED_GROUP1,AGE_GROUPED_GROUP2,AGE_GROUPED_GROUP3,AGE_GROUPED_GROUP4,NUMBER_OF_MEMBERS_BIN_GROUP1,NUMBER_OF_MEMBERS_BIN_GROUP2,NUMBER_OF_MEMBERS_BIN_GROUP3
889431,0,0,0,0,0,False,True,False,True,False,True,True,False,True,False,True,False,True,False,False,True,False,False,False,True,True,False,True,False,True,False,False,False,False,False,False,True,True,False,False,False,True,True,False,False,False,False,False,True,False,True,False,False
846194,0,1,0,1,0,False,True,True,False,False,True,True,False,False,True,False,True,False,True,False,True,False,False,True,False,False,True,True,False,False,False,False,True,False,True,False,False,False,False,True,False,True,False,False,False,True,False,True,False,False,False,True,False
492622,0,0,0,0,0,False,True,False,True,False,True,True,False,False,True,True,False,True,False,True,False,False,False,False,True,True,False,False,True,False,False,False,True,False,True,False,False,False,True,False,False,True,False,False,True,False,False,False,True,False,True,False,False
197334,1,1,0,0,0,False,True,True,False,False,True,True,False,False,True,True,False,True,False,False,True,False,False,False,True,True,False,True,False,False,False,False,True,False,True,False,False,False,False,True,False,True,False,False,False,True,False,False,True,False,False,False,True
698020,0,0,0,0,0,True,False,False,True,False,True,True,False,False,True,True,False,True,False,False,True,False,False,False,True,True,False,False,True,False,False,False,True,True,False,False,False,False,False,True,False,True,True,False,False,False,True,False,False,False,True,False,False

In [141]:
#Repeating the same for validation and training data

In [142]:
df2 = df_test[c]

cat_vars = [i for i in df2.columns if df2[i].dtype == 'object']

for var in cat_vars:
    dummies = pd.get_dummies(df2[var], prefix=var)
    df2 = df2.join(dummies)

df2 = df2.drop(cat_vars, axis=1)

In [143]:
df3 = df_val[c]

cat_vars = [i for i in df3.columns if df3[i].dtype == 'object']

for var in cat_vars:
    dummies = pd.get_dummies(df3[var], prefix=var)
    df3 = df3.join(dummies)

df3 = df3.drop(cat_vars, axis=1)

In [144]:
print(df1.shape)
print(df2.shape)
print(df3.shape)

(571831, 53)
(245071, 53)
(204226, 53)

In [145]:
# Find common columns across all three
common_columns = set(df1.columns) & set(df2.columns) & set(df3.columns)

# Keep only the common columns
df1 = df1[list(common_columns)]
df2 = df2[list(common_columns)]
df3 = df3[list(common_columns)]

In [146]:
print("Train shape:", df1.shape)
print("Test shape:", df2.shape)
print("Validation shape:", df3.shape)

Train shape: (571831, 53)
Test shape: (245071, 53)
Validation shape: (204226, 53)

In [147]:
list1 = df1.columns.tolist()

In [148]:
list1

['NUMBER_OF_MEMBERS_BIN_GROUP1',
 'POLICY_VINTAGE_REVISED_13TH MONTH',
 'OCCUPATION_BIN_GROUP4',
 'BUSINESSTYPE_RENEWAL BUSINESS',
 'POLICYVARIANT_INDIVIDUAL',
 'ADULT_CNT_>=2',
 'BMI_0-18',
 'REPORTING_YEAR_R0',
 'AGE_GROUPED_GROUP4',
 'POLICYVARIANT_FAMILY FLOATER',
 'PLAN TYPE ORIGINAL_BIN_GROUP1',
 'STATE_BIN_GROUP1',
 'ACTIVEDAYS ORIGINAL_BIN',
 'CHANNEL_OTHER',
 'PLAN TYPE ORIGINAL_BIN_GROUP3',
 'MARITALSTATUS_BIN_GROUP2',
 'NUMBER_OF_MEMBERS_BIN_GROUP3',
 'TARGET',
 'STATE_BIN_GROUP4',
 'AGE_GROUPED_GROUP1',
 'ACTIVEDAYS_CNT_BIN',
 'CHANNEL_TPD',
 'REPORTING_YEAR_>R0',
 'PRODUCT NAME_BIN_GROUP3',
 'GENDER_F',
 'AGE_GROUPED_GROUP3',
 'BUSINESSTYPE_OTHER',
 'BMI_>35',
 'OCCUPATION_BIN_GROUP3',
 'OCCUPATION_BIN_GROUP1',
 'PORTABILITYFLAG_NO',
 'STP / NSTP_STP',
 'PLAN TYPE ORIGINAL_BIN_GROUP4',
 'STP / NSTP_NSTP',
 'OCCUPATION_BIN_GROUP2',
 'STATE_BIN_GROUP2',
 'BMI_27-35',
 'PRODUCT NAME_BIN_GROUP1',
 'GENDER_M',
 'POLICY_VINTAGE_REVISED_>13TH MONTH',
 'PLAN TYPE ORIGINAL_BIN_GROUP2',
 'NUMBER_OF_MEMBERS_BIN_GROUP2',
 'STATE_BIN_GROUP3',
 'ADULT_CNT_<2',
 'BMI_18-27',
 'HHS_CNT',
 'MARITALSTATUS_BIN_GROUP1',
 'APPLOGIN_CNT',
 'PORTABILITYFLAG_YES',
 'AGE_GROUPED_GROUP2',
 'PRODUCT NAME_BIN_GROUP2',
 'POLICYTENURE_BIN_1',
 'POLICYTENURE_BIN_1']

In [149]:
#Splitting the data into X_train and Y_test for Train, validation and test dataframe

In [150]:
X_train=df1.drop(['TARGET'],axis=1)
y_train=train['TARGET']

In [151]:
X_train

,NUMBER_OF_MEMBERS_BIN_GROUP1,POLICY_VINTAGE_REVISED_13TH MONTH,OCCUPATION_BIN_GROUP4,BUSINESSTYPE_RENEWAL BUSINESS,POLICYVARIANT_INDIVIDUAL,ADULT_CNT_>=2,BMI_0-18,REPORTING_YEAR_R0,AGE_GROUPED_GROUP4,POLICYVARIANT_FAMILY FLOATER,PLAN TYPE ORIGINAL_BIN_GROUP1,STATE_BIN_GROUP1,ACTIVEDAYS ORIGINAL_BIN,CHANNEL_OTHER,PLAN TYPE ORIGINAL_BIN_GROUP3,MARITALSTATUS_BIN_GROUP2,NUMBER_OF_MEMBERS_BIN_GROUP3,STATE_BIN_GROUP4,AGE_GROUPED_GROUP1,ACTIVEDAYS_CNT_BIN,CHANNEL_TPD,REPORTING_YEAR_>R0,PRODUCT NAME_BIN_GROUP3,GENDER_F,AGE_GROUPED_GROUP3,BUSINESSTYPE_OTHER,BMI_>35,OCCUPATION_BIN_GROUP3,OCCUPATION_BIN_GROUP1,PORTABILITYFLAG_NO,STP / NSTP_STP,PLAN TYPE ORIGINAL_BIN_GROUP4,STP / NSTP_NSTP,OCCUPATION_BIN_GROUP2,STATE_BIN_GROUP2,BMI_27-35,PRODUCT NAME_BIN_GROUP1,GENDER_M,POLICY_VINTAGE_REVISED_>13TH MONTH,PLAN TYPE ORIGINAL_BIN_GROUP2,NUMBER_OF_MEMBERS_BIN_GROUP2,STATE_BIN_GROUP3,ADULT_CNT_<2,BMI_18-27,HHS_CNT,MARITALSTATUS_BIN_GROUP1,APPLOGIN_CNT,PORTABILITYFLAG_YES,AGE_GROUPED_GROUP2,PRODUCT NAME_BIN_GROUP2,POLICYTENURE_BIN_1,POLICYTENURE_BIN_1
889431,True,True,False,False,True,False,False,True,False,False,True,False,0,True,False,False,False,True,False,0,False,False,False,False,True,True,False,False,True,True,True,False,False,False,False,False,True,True,False,False,False,False,True,True,0,True,0,False,False,False,False,True
846194,False,False,True,True,False,False,False,False,False,True,False,False,1,False,False,False,False,False,False,0,True,True,True,False,False,False,False,False,False,False,True,True,False,False,True,False,False,True,True,False,True,False,True,True,0,True,1,True,True,False,False,True
492622,True,True,True,False,True,False,True,True,False,False,False,False,0,False,True,True,False,False,False,0,True,False,False,False,True,True,False,False,False,True,True,False,False,False,True,False,False,True,False,False,False,False,True,False,0,False,0,False,False,True,False,True
197334,False,True,True,False,False,False,False,True,False,True,False,False,0,False,False,False,True,False,False,0,True,False,True,False,True,True,False,False,False,True,True,True,False,False,True,False,False,True,False,False,False,False,True,True,1,True,1,False,False,False,False,True
698020,True,True,True,False,True,False,False,True,False,False,True,True,0,False,False,True,False,False,True,0,True,False,True,True,False,True,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,True,True,0,False,0,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
538697,True,True,False,False,True,False,False,True,False,False,True,False,0,False,False,True,False,False,False,0,True,False,True,False,True,True,False,False,False,True,True,False,False,True,False,True,False,True,False,False,False,True,True,False,0,False,0,False,False,False,False,True
403922,False,True,True,False,False,True,False,True,False,True,False,False,0,True,False,False,True,False,False,0,False,False,False,False,True,True,False,False,False,True,True,True,False,False,True,True,False,True,False,False,False,False,False,False,0,True,1,False,False,True,False,True
117802,True,False,False,True,True,True,False,False,False,False,False,False,0,True,False,True,False,False,False,0,False,True,True,True,True,False,False,False,True,True,False,True,True,False,True,False,False,False,True,False,False,False,False,True,0,False,0,False,False,False,False,True
455768,True,True,False,False,True,False,False,True,False,False,True,False,0,False,False,True,False,False,True,0,True,False,False,False,False,True,False,False,False,True,True,False,False,True,True,False,True,True,False,False,False,False,True,True,0,False,0,False,False,False,False,True
96660,True,True,False,False,True,True,False,True,False,False,True,False,0,True,False,False,False,False,False,0,False,False,False,True,False,True,False,True,False,True,True,False,False,False,True,True,True,False,False,False,False,False,False,False,0,True,0,False,True,False,False,True

In [152]:
y_train

889431    0
846194    0
492622    0
197334    0
698020    0
         ..
538697    0
403922    1
117802    0
455768    0
96660     0
Name: TARGET, Length: 571831, dtype: int64

In [153]:
X_test=df2.drop(['TARGET'],axis=1)
y_test=test['TARGET']

In [154]:
X_val=df3.drop(['TARGET'],axis=1)
y_val=val['TARGET']

In [155]:
print(X_train.shape)
print(X_test.shape)
print(X_val.shape)

(571831, 52)
(245071, 52)
(204226, 52)

# Using Xgboost

In [157]:
#sanitize the column names 
X_train.columns = X_train.columns.astype(str).str.replace(r"[<>\[\]]", "_", regex=True)
X_test.columns = X_test.columns.astype(str).str.replace(r"[<>\[\]]", "_", regex=True)
X_val.columns = X_val.columns.astype(str).str.replace(r"[<>\[\]]", "_", regex=True)

In [158]:
X_train.columns

Index(['NUMBER_OF_MEMBERS_BIN_GROUP1', 'POLICY_VINTAGE_REVISED_13TH MONTH',
       'OCCUPATION_BIN_GROUP4', 'BUSINESSTYPE_RENEWAL BUSINESS',
       'POLICYVARIANT_INDIVIDUAL', 'ADULT_CNT__=2', 'BMI_0-18',
       'REPORTING_YEAR_R0', 'AGE_GROUPED_GROUP4',
       'POLICYVARIANT_FAMILY FLOATER', 'PLAN TYPE ORIGINAL_BIN_GROUP1',
       'STATE_BIN_GROUP1', 'ACTIVEDAYS ORIGINAL_BIN', 'CHANNEL_OTHER',
       'PLAN TYPE ORIGINAL_BIN_GROUP3', 'MARITALSTATUS_BIN_GROUP2',
       'NUMBER_OF_MEMBERS_BIN_GROUP3', 'STATE_BIN_GROUP4',
       'AGE_GROUPED_GROUP1', 'ACTIVEDAYS_CNT_BIN', 'CHANNEL_TPD',
       'REPORTING_YEAR__R0', 'PRODUCT NAME_BIN_GROUP3', 'GENDER_F',
       'AGE_GROUPED_GROUP3', 'BUSINESSTYPE_OTHER', 'BMI__35',
       'OCCUPATION_BIN_GROUP3', 'OCCUPATION_BIN_GROUP1', 'PORTABILITYFLAG_NO',
       'STP / NSTP_STP', 'PLAN TYPE ORIGINAL_BIN_GROUP4', 'STP / NSTP_NSTP',
       'OCCUPATION_BIN_GROUP2', 'STATE_BIN_GROUP2', 'BMI_27-35',
       'PRODUCT NAME_BIN_GROUP1', 'GENDER_M',
       'POLICY_VINTAGE_REVISED__13TH MONTH', 'PLAN TYPE ORIGINAL_BIN_GROUP2',
       'NUMBER_OF_MEMBERS_BIN_GROUP2', 'STATE_BIN_GROUP3', 'ADULT_CNT__2',
       'BMI_18-27', 'HHS_CNT', 'MARITALSTATUS_BIN_GROUP1', 'APPLOGIN_CNT',
       'PORTABILITYFLAG_YES', 'AGE_GROUPED_GROUP2', 'PRODUCT NAME_BIN_GROUP2',
       'POLICYTENURE_BIN_1', 'POLICYTENURE_BIN_1'],
      dtype='object')

In [159]:
# Xgboost model

In [160]:
# Count of classes in training data
num_0 = sum(y_train == 0)
num_1 = sum(y_train == 1)

# Ratio of majority to minority class
scale_pos_weight = num_0 / num_1
print("scale_pos_weight:", scale_pos_weight)

scale_pos_weight: 14.55494804417605

In [164]:
y_train

889431    0
846194    0
492622    0
197334    0
698020    0
         ..
538697    0
403922    1
117802    0
455768    0
96660     0
Name: TARGET, Length: 571831, dtype: int64

In [165]:
X_train

,NUMBER_OF_MEMBERS_BIN_GROUP1,POLICY_VINTAGE_REVISED_13TH MONTH,OCCUPATION_BIN_GROUP4,BUSINESSTYPE_RENEWAL BUSINESS,POLICYVARIANT_INDIVIDUAL,ADULT_CNT__=2,BMI_0-18,REPORTING_YEAR_R0,AGE_GROUPED_GROUP4,POLICYVARIANT_FAMILY FLOATER,PLAN TYPE ORIGINAL_BIN_GROUP1,STATE_BIN_GROUP1,ACTIVEDAYS ORIGINAL_BIN,CHANNEL_OTHER,PLAN TYPE ORIGINAL_BIN_GROUP3,MARITALSTATUS_BIN_GROUP2,NUMBER_OF_MEMBERS_BIN_GROUP3,STATE_BIN_GROUP4,AGE_GROUPED_GROUP1,ACTIVEDAYS_CNT_BIN,CHANNEL_TPD,REPORTING_YEAR__R0,PRODUCT NAME_BIN_GROUP3,GENDER_F,AGE_GROUPED_GROUP3,BUSINESSTYPE_OTHER,BMI__35,OCCUPATION_BIN_GROUP3,OCCUPATION_BIN_GROUP1,PORTABILITYFLAG_NO,STP / NSTP_STP,PLAN TYPE ORIGINAL_BIN_GROUP4,STP / NSTP_NSTP,OCCUPATION_BIN_GROUP2,STATE_BIN_GROUP2,BMI_27-35,PRODUCT NAME_BIN_GROUP1,GENDER_M,POLICY_VINTAGE_REVISED__13TH MONTH,PLAN TYPE ORIGINAL_BIN_GROUP2,NUMBER_OF_MEMBERS_BIN_GROUP2,STATE_BIN_GROUP3,ADULT_CNT__2,BMI_18-27,HHS_CNT,MARITALSTATUS_BIN_GROUP1,APPLOGIN_CNT,PORTABILITYFLAG_YES,AGE_GROUPED_GROUP2,PRODUCT NAME_BIN_GROUP2,POLICYTENURE_BIN_1,POLICYTENURE_BIN_1
889431,True,True,False,False,True,False,False,True,False,False,True,False,0,True,False,False,False,True,False,0,False,False,False,False,True,True,False,False,True,True,True,False,False,False,False,False,True,True,False,False,False,False,True,True,0,True,0,False,False,False,False,True
846194,False,False,True,True,False,False,False,False,False,True,False,False,1,False,False,False,False,False,False,0,True,True,True,False,False,False,False,False,False,False,True,True,False,False,True,False,False,True,True,False,True,False,True,True,0,True,1,True,True,False,False,True
492622,True,True,True,False,True,False,True,True,False,False,False,False,0,False,True,True,False,False,False,0,True,False,False,False,True,True,False,False,False,True,True,False,False,False,True,False,False,True,False,False,False,False,True,False,0,False,0,False,False,True,False,True
197334,False,True,True,False,False,False,False,True,False,True,False,False,0,False,False,False,True,False,False,0,True,False,True,False,True,True,False,False,False,True,True,True,False,False,True,False,False,True,False,False,False,False,True,True,1,True,1,False,False,False,False,True
698020,True,True,True,False,True,False,False,True,False,False,True,True,0,False,False,True,False,False,True,0,True,False,True,True,False,True,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,True,True,0,False,0,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
538697,True,True,False,False,True,False,False,True,False,False,True,False,0,False,False,True,False,False,False,0,True,False,True,False,True,True,False,False,False,True,True,False,False,True,False,True,False,True,False,False,False,True,True,False,0,False,0,False,False,False,False,True
403922,False,True,True,False,False,True,False,True,False,True,False,False,0,True,False,False,True,False,False,0,False,False,False,False,True,True,False,False,False,True,True,True,False,False,True,True,False,True,False,False,False,False,False,False,0,True,1,False,False,True,False,True
117802,True,False,False,True,True,True,False,False,False,False,False,False,0,True,False,True,False,False,False,0,False,True,True,True,True,False,False,False,True,True,False,True,True,False,True,False,False,False,True,False,False,False,False,True,0,False,0,False,False,False,False,True
455768,True,True,False,False,True,False,False,True,False,False,True,False,0,False,False,True,False,False,True,0,True,False,False,False,False,True,False,False,False,True,True,False,False,True,True,False,True,True,False,False,False,False,True,True,0,False,0,False,False,False,False,True
96660,True,True,False,False,True,True,False,True,False,False,True,False,0,True,False,False,False,False,False,0,False,False,False,True,False,True,False,True,False,True,True,False,False,False,True,True,True,False,False,False,False,False,False,False,0,True,0,False,True,False,False,True

In [173]:
# Flatten column names in case they're tuples (multi-index from one-hot)
def flatten_columns(df):
    df.columns = ['_'.join(map(str, col)) if isinstance(col, tuple) else str(col) for col in df.columns]
    return df

X_train = flatten_columns(X_train)
X_test = flatten_columns(X_test)
X_val = flatten_columns(X_val)

In [175]:
#Converting it into numeric values
X_train = X_train.astype(float)
X_test = X_test.astype(float)
X_val = X_val.astype(float)

In [177]:
import xgboost as xgb
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pandas as pd

# Initialize the classifier with scale_pos_weight
xgb_cl = xgb.XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=5,
    subsample=0.8,
    colsample_bytree=0.8,
    use_label_encoder=False,
    eval_metric='logloss',
    scale_pos_weight=scale_pos_weight,  # <--- This handles imbalance
    random_state=42
)

In [187]:
# Train the model on training data
xgb_cl.fit(X_train.values, y_train.values)

# Predict on train, test, and validation data
y_train_pred = xgb_cl.predict(X_train.values)
y_test_pred = xgb_cl.predict(X_test.values)
y_val_pred = xgb_cl.predict(X_val.values)

# Evaluate accuracy
print("Train Accuracy:", accuracy_score(y_train, y_train_pred))
print("Test Accuracy:", accuracy_score(y_test, y_test_pred))
print("Validation Accuracy:", accuracy_score(y_val, y_val_pred))

# Detailed report
print("\nClassification Report (Validation):")
print(classification_report(y_val, y_val_pred))

print("\nConfusion Matrix (Validation):")
print(confusion_matrix(y_val, y_val_pred))

C:\Users\Admin\anaconda3\Lib\site-packages\xgboost\training.py:183: UserWarning: [20:09:11] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Train Accuracy: 0.6094580391759103
Test Accuracy: 0.6084032790497448
Validation Accuracy: 0.611562680559772

Classification Report (Validation):
              precision    recall  f1-score   support

           0       0.98      0.60      0.74    190975
           1       0.12      0.81      0.21     13251

    accuracy                           0.61    204226
   macro avg       0.55      0.70      0.48    204226
weighted avg       0.92      0.61      0.71    204226


Confusion Matrix (Validation):
[[114157  76818]
 [  2511  10740]]

In [189]:
# Feature importance
feat_imp = pd.DataFrame({
    'Feature': X_train.columns,
    'Importance': xgb_cl.feature_importances_ * 100
}).sort_values(by='Importance', ascending=False).reset_index(drop=True)

print("\nTop Feature Importances:")
print(feat_imp.head(10))

Top Feature Importances:
                         Feature  Importance
0                   ADULT_CNT__2   20.751644
1                      BMI_18-27   16.573616
2                  ADULT_CNT__=2   11.544524
3                 STP / NSTP_STP    5.043353
4                STP / NSTP_NSTP    3.985048
5        PRODUCT NAME_BIN_GROUP1    3.689656
6                    CHANNEL_TPD    2.478868
7  PLAN TYPE ORIGINAL_BIN_GROUP2    2.280509
8                        BMI__35    2.210497
9                  CHANNEL_OTHER    1.907779

In [191]:
# Define a threshold
threshold = 1.0  # Features with importance < 1% will be removed

# Filter the features to keep
important_features = feat_imp[feat_imp['Importance'] >= threshold]['Feature'].tolist()

# Reduce X_train, X_test, and X_val to only the important features
X_train_reduced = X_train[important_features]
X_test_reduced = X_test[important_features]
X_val_reduced = X_val[important_features]

In [195]:
# Train again using only important features
xgb_cl.fit(X_train_reduced.values, y_train)

# Predict again
y_train_pred = xgb_cl.predict(X_train_reduced.values)
y_test_pred = xgb_cl.predict(X_test_reduced.values)
y_val_pred = xgb_cl.predict(X_val_reduced.values)

# Evaluate again
print("Training Accuracy (Reduced):", accuracy_score(y_train, y_train_pred))
print("Testing Accuracy (Reduced):", accuracy_score(y_test, y_test_pred))
print("Validation Accuracy (Reduced):", accuracy_score(y_val, y_val_pred))

C:\Users\Admin\anaconda3\Lib\site-packages\xgboost\training.py:183: UserWarning: [20:10:41] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Training Accuracy (Reduced): 0.6121826203895906
Testing Accuracy (Reduced): 0.6116676391739537
Validation Accuracy (Reduced): 0.614461429984429

In [197]:
# Detailed classification report
print("\nClassification Report (Validation):")
print(classification_report(y_val, y_val_pred))

Classification Report (Validation):
              precision    recall  f1-score   support

           0       0.98      0.60      0.74    190975
           1       0.12      0.80      0.21     13251

    accuracy                           0.61    204226
   macro avg       0.55      0.70      0.48    204226
weighted avg       0.92      0.61      0.71    204226

In [199]:
print("\nConfusion Matrix (Validation):")
print(confusion_matrix(y_val, y_val_pred))

Confusion Matrix (Validation):
[[114954  76021]
 [  2716  10535]]

In [201]:
'''
Metric	Value
True Negatives (TN)	114,954
False Positives (FP)	76,021 (class 0 → predicted 1)
False Negatives (FN)	2,716 (class 1 → predicted 0)
True Positives (TP)	10,535
'''

'\nMetric\tValue\nTrue Negatives (TN)\t114,954\nFalse Positives (FP)\t76,021 (class 0 → predicted 1)\nFalse Negatives (FN)\t2,716 (class 1 → predicted 0)\nTrue Positives (TP)\t10,535\n'

In [209]:
df['POLICYSTARTDATE'].min()

'2019-04-01 00:00:00.000'

In [213]:
df['POLICYENDDATE'].min()

'2019-04-01 00:00:00.000'

In [215]:
df['POLICYSTARTDATE'].max()

'2022-08-27 00:00:00.000'

In [217]:
feat_imp

                               Feature  Importance
0                         ADULT_CNT__2   20.751644
1                            BMI_18-27   16.573616
2                        ADULT_CNT__=2   11.544524
3                       STP / NSTP_STP    5.043353
4                      STP / NSTP_NSTP    3.985048
5              PRODUCT NAME_BIN_GROUP1    3.689656
6                          CHANNEL_TPD    2.478868
7        PLAN TYPE ORIGINAL_BIN_GROUP2    2.280509
8                              BMI__35    2.210497
9                        CHANNEL_OTHER    1.907779
10                  POLICYTENURE_BIN_1    1.718724
11   POLICY_VINTAGE_REVISED_13TH MONTH    1.616939
12               OCCUPATION_BIN_GROUP4    1.538012
13                  REPORTING_YEAR__R0    1.404077
14       BUSINESSTYPE_RENEWAL BUSINESS    1.366154
15                    STATE_BIN_GROUP4    1.325310
16       PLAN TYPE ORIGINAL_BIN_GROUP1    1.233903
17                             HHS_CNT    1.192025
18       PLAN TYPE ORIGINAL_BIN_GROUP4    1.150187
19                  PORTABILITYFLAG_NO    1.089961
20                  BUSINESSTYPE_OTHER    1.086623
21                   REPORTING_YEAR_R0    1.082541
22            MARITALSTATUS_BIN_GROUP2    0.964555
23                            BMI_0-18    0.950270
24                  POLICYTENURE_BIN_1    0.792708
25             PRODUCT NAME_BIN_GROUP2    0.759110
26                  AGE_GROUPED_GROUP1    0.702383
27  POLICY_VINTAGE_REVISED__13TH MONTH    0.701470
28            MARITALSTATUS_BIN_GROUP1    0.687499
29       PLAN TYPE ORIGINAL_BIN_GROUP3    0.666291
30                    STATE_BIN_GROUP2    0.620606
31             PRODUCT NAME_BIN_GROUP3    0.601227
32                            GENDER_F    0.546405
33                        APPLOGIN_CNT    0.452221
34                 PORTABILITYFLAG_YES    0.433549
35        NUMBER_OF_MEMBERS_BIN_GROUP1    0.432921
36            POLICYVARIANT_INDIVIDUAL    0.404139
37                  AGE_GROUPED_GROUP4    0.402536
38                            GENDER_M    0.386464
39               OCCUPATION_BIN_GROUP3    0.344255
40               OCCUPATION_BIN_GROUP2    0.316755
41                  ACTIVEDAYS_CNT_BIN    0.310666
42               OCCUPATION_BIN_GROUP1    0.277151
43                    STATE_BIN_GROUP3    0.252434
44                           BMI_27-35    0.247940
45                    STATE_BIN_GROUP1    0.244318
46             ACTIVEDAYS ORIGINAL_BIN    0.241206
47        NUMBER_OF_MEMBERS_BIN_GROUP3    0.234143
48                  AGE_GROUPED_GROUP3    0.218455
49        NUMBER_OF_MEMBERS_BIN_GROUP2    0.187934
50                  AGE_GROUPED_GROUP2    0.183051
51        POLICYVARIANT_FAMILY FLOATER    0.167379